server.port=8080
server.address=0.0.0.0


# Cấu hình Spring Data JPA / Hibernate
spring.datasource.url=jdbc:h2:mem:luminadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (để truy cập xem database trực tiếp trên trình duyệt tại http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Cấu hình JWT (JSON Web Token)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Access token: 60 phút (3600000 ms)
jwt.expiration-ms=3600000
# Refresh token: 7 ngày (604800000 ms)
jwt.refresh-expiration-ms=604800000

# Tuỳ chọn nếu sau này bạn muốn chuyển sang MySQL:
# spring.datasource.url=jdbc:mysql://localhost:3306/lumina_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=yourpassword
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
