package com.lumina.backend.config

import com.lumina.backend.model.entity.Vocabulary

/**
 * Danh mục 504 từ vựng chuẩn HSK 1 (Phần 1: Từ 1 đến 252)
 * Chuẩn khung HSK 3.0 Band 1 (Căn bản)
 */
object Hsk1DataPart1 {

    private fun v(
        hanzi: String, pinyin: String, hanViet: String, meaning: String,
        partOfSpeech: String, topic: String, radical: String, strokes: String,
        exHz: String, exPy: String, exM: String
    ): Vocabulary = Vocabulary(
        hanzi = hanzi, pinyin = pinyin, hanViet = hanViet, meaning = meaning,
        partOfSpeech = partOfSpeech, topic = topic, radical = radical, strokes = strokes,
        exampleHanzi = exHz, examplePinyin = exPy, exampleMeaning = exM,
        hskLevel = "HSK 1", targetScore = "HSK 1 (Mục tiêu 180–200/200 điểm)"
    )

    val words: List<Vocabulary> by lazy {
        listOf(
            // ── 1. ĐẠI TỪ & CHỈ THỊ (PRONOUNS) ──
            v("我", "wǒ", "Ngã", "Tôi, tao, mình", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 戈 (Qua)", "7 nét", "我是学生。", "Wǒ shì xuésheng.", "Tôi là học sinh."),
            v("你", "nǐ", "Nhĩ", "Bạn, cậu, mày", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 亻 (Nhân)", "7 nét", "你好吗？", "Nǐ hǎo ma?", "Bạn có khỏe không?"),
            v("您", "nín", "Nẫm", "Ngài, ông, bà (kính trọng)", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 心 (Tâm)", "11 nét", "老师，您好！", "Lǎoshī, nín hǎo!", "Kính chào thầy cô ạ!"),
            v("他", "tā", "Tha", "Anh ấy, ông ấy, cậu ấy", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 亻 (Nhân)", "5 nét", "他是我的朋友。", "Tā shì wǒ de péngyou.", "Anh ấy là bạn của tôi."),
            v("她", "tā", "Tha", "Cô ấy, bà ấy, chị ấy", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 女 (Nữ)", "6 nét", "她是汉语老师。", "Tā shì Hànyǔ lǎoshī.", "Cô ấy là giáo viên tiếng Trung."),
            v("它", "tā", "Tha", "Nó (chỉ đồ vật, con vật)", "Đại từ", "Động vật & Thiên nhiên", "Bộ: 宀 (Miên)", "5 nét", "它是一只小猫。", "Tā shì yì zhī xiǎomāo.", "Nó là một con mèo nhỏ."),
            v("我们", "wǒmen", "Ngã Môn", "Chúng tôi, chúng ta", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 亻 (Nhân)", "12 nét", "我们都去北京。", "Wǒmen dōu qù Běijīng.", "Chúng tôi đều đi Bắc Kinh."),
            v("你们", "nǐmen", "Nhĩ Môn", "Các bạn, các cậu", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 亻 (Nhân)", "12 nét", "你们好！", "Nǐmen hǎo!", "Chào các bạn!"),
            v("他们", "tāmen", "Tha Môn", "Họ, bọn họ (nam/chung)", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 亻 (Nhân)", "10 nét", "他们正在开会。", "Tāmen zhèngzài kāihuì.", "Họ đang họp."),
            v("她们", "tāmen", "Tha Môn", "Các cô ấy, bọn họ (nữ)", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 女 (Nữ)", "11 nét", "她们都是医生。", "Tāmen dōu shì yīshēng.", "Các cô ấy đều là bác sĩ."),
            v("它们", "tāmen", "Tha Môn", "Chúng nó (động vật, đồ vật)", "Đại từ", "Động vật & Thiên nhiên", "Bộ: 宀 (Miên)", "10 nét", "它们都很可爱。", "Tāmen dōu hěn kě'ài.", "Chúng nó đều rất đáng yêu."),
            v("这", "zhè", "Giá", "Đây, này", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 辶 (Sước)", "7 nét", "这是什么？", "Zhè shì shénme?", "Đây là cái gì?"),
            v("这儿", "zhèr", "Giá Nhi", "Ở đây, chỗ này", "Đại từ", "Phương hướng & Vị trí", "Bộ: 辶 (Sước)", "9 nét", "请坐在这儿。", "Qǐng zuò zài zhèr.", "Xin mời ngồi ở đây."),
            v("这里", "zhèlǐ", "Giá Lý", "Ở đây, nơi này", "Đại từ", "Phương hướng & Vị trí", "Bộ: 辶 (Sước)", "14 nét", "这里天气很好。", "Zhèlǐ tiānqì hěn hǎo.", "Thời tiết ở đây rất đẹp."),
            v("那", "nà", "Na", "Kia, đó", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 阝 (Ấp)", "6 nét", "那是我的书。", "Nà shì wǒ de shū.", "Đó là sách của tôi."),
            v("那儿", "nàr", "Na Nhi", "Ở kia, đằng kia", "Đại từ", "Phương hướng & Vị trí", "Bộ: 阝 (Ấp)", "8 nét", "学校在那儿。", "Xuéxiào zài nàr.", "Trường học ở đằng kia."),
            v("那里", "nàlǐ", "Na Lý", "Nơi đó, chỗ đó", "Đại từ", "Phương hướng & Vị trí", "Bộ: 阝 (Ấp)", "13 nét", "我想去那里。", "Wǒ xiǎng qù nàlǐ.", "Tôi muốn đi đến nơi đó."),
            v("哪", "nǎ", "Nả", "Nào", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 口 (Khẩu)", "9 nét", "你是哪国人？", "Nǐ shì nǎ guó rén?", "Bạn là người nước nào?"),
            v("哪儿", "nǎr", "Nả Nhi", "Ở đâu, chỗ nào", "Đại từ", "Phương hướng & Vị trí", "Bộ: 口 (Khẩu)", "11 nét", "你去哪儿？", "Nǐ qù nǎr?", "Bạn đi đâu đấy?"),
            v("哪里", "nǎlǐ", "Nả Lý", "Đâu, ở đâu / Đâu có (khiêm tốn)", "Đại từ", "Phương hướng & Vị trí", "Bộ: 口 (Khẩu)", "16 nét", "哪里，您过奖了。", "Nǎlǐ, nín guòjiǎng le.", "Đâu có, bạn quá khen rồi."),
            v("谁", "shéi", "Thùy", "Ai, người nào", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 讠 (Ngôn)", "10 nét", "他是谁？", "Tā shì shéi?", "Anh ấy là ai?"),
            v("什么", "shénme", "Thập Ma", "Cái gì, gì", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 亻 (Nhân)", "7 nét", "你叫什么名字？", "Nǐ jiào shénme míngzi?", "Bạn tên là gì?"),
            v("怎么", "zěnme", "Chẩm Ma", "Thế nào, làm sao", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 心 (Tâm)", "12 nét", "你怎么了？", "Nǐ zěnme le?", "Bạn làm sao thế?"),
            v("怎么样", "zěnmeyàng", "Chẩm Ma Dạng", "Như thế nào, ra sao", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 心 (Tâm)", "21 nét", "今天天气怎么样？", "Jīntiān tiānqì zěnmeyàng?", "Hôm nay thời tiết thế nào?"),
            v("几", "jǐ", "Kỷ", "Mấy (dưới 10)", "Đại từ / Số từ", "Mua sắm & Trả giá", "Bộ: 几 (Kỷ)", "2 nét", "现在几点了？", "Xiànzài jǐ diǎn le?", "Bây giờ là mấy giờ rồi?"),
            v("多少", "duōshao", "Đa Thiểu", "Bao nhiêu", "Đại từ", "Mua sắm & Trả giá", "Bộ: 夕 (Tịch)", "10 nét", "这个多少钱？", "Zhège duōshao qián?", "Cái này bao nhiêu tiền?"),
            v("为什么", "wèishénme", "Vi Thập Ma", "Tại sao, vì sao", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 丶 (Chủ)", "11 nét", "你为什么迟到？", "Nǐ wèishénme chídào?", "Tại sao bạn lại đến muộn?"),
            v("自己", "zìjǐ", "Tự Kỷ", "Bản thân, tự mình", "Đại từ", "Gia đình & Đời sống", "Bộ: 自 (Tự)", "9 nét", "我自己去买。", "Wǒ zìjǐ qù mǎi.", "Tôi tự mình đi mua."),
            v("大家", "dàjiā", "Đại Gia", "Mọi người, tất cả", "Đại từ", "Chào hỏi & Giao tiếp", "Bộ: 大 (Đại)", "13 nét", "请大家安静。", "Qǐng dàjiā ānjìng.", "Xin mọi người trật tự."),
            v("别的", "biéde", "Biệt Đích", "Cái khác, người khác", "Đại từ", "Mua sắm & Trả giá", "Bộ: 刂 (Đao)", "15 nét", "还要别的吗？", "Hái yào biéde ma?", "Còn cần cái gì khác không?"),
            v("其他", "qítā", "Kỳ Tha", "Khác, còn lại", "Đại từ", "Học tập & Giáo dục", "Bộ: 八 (Bát)", "13 nét", "其他人都走了。", "Qítā rén dōu zǒu le.", "Những người khác đều đi rồi."),
            v("每", "měi", "Mỗi", "Mỗi, từng", "Đại từ", "Thời gian & Ngày tháng", "Bộ: 母 (Mẫu)", "7 nét", "我每天学习汉语。", "Wǒ měitiān xuéxí Hànyǔ.", "Mỗi ngày tôi đều học tiếng Trung."),

            // ── 2. SỐ TỪ (NUMBERS) ──
            v("零", "líng", "Linh", "Số không (0)", "Số từ", "Mua sắm & Trả giá", "Bộ: 雨 (Vũ)", "13 nét", "我的房间是三零一。", "Wǒ de fángjiān shì sān líng yī.", "Phòng tôi là 301."),
            v("一", "yī", "Nhất", "Một (1)", "Số từ", "Mua sắm & Trả giá", "Bộ: 一 (Nhất)", "1 nét", "一个人。", "Yí gè rén.", "Một người."),
            v("二", "èr", "Nhị", "Hai (2)", "Số từ", "Mua sắm & Trả giá", "Bộ: 二 (Nhị)", "2 nét", "星期二。", "Xīngqī'èr.", "Thứ ba."),
            v("两", "liǎng", "Lưỡng", "Hai (dùng trước lượng từ)", "Số từ", "Mua sắm & Trả giá", "Bộ: 一 (Nhất)", "7 nét", "两个苹果。", "Liǎng gè píngguǒ.", "Hai quả táo."),
            v("三", "sān", "Tam", "Ba (3)", "Số từ", "Mua sắm & Trả giá", "Bộ: 一 (Nhất)", "3 nét", "三本书。", "Sān běn shū.", "Ba quyển sách."),
            v("四", "sì", "Tứ", "Bốn (4)", "Số từ", "Mua sắm & Trả giá", "Bộ: 囗 (Vi)", "5 nét", "四点钟。", "Sì diǎn zhōng.", "Bốn giờ đúng."),
            v("五", "wǔ", "Ngũ", "Năm (5)", "Số từ", "Mua sắm & Trả giá", "Bộ: 二 (Nhị)", "4 nét", "五月五日。", "Wǔ yuè wǔ rì.", "Ngày 5 tháng 5."),
            v("六", "liù", "Lục", "Sáu (6)", "Số từ", "Mua sắm & Trả giá", "Bộ: 八 (Bát)", "4 nét", "六个人。", "Liù gè rén.", "Sáu người."),
            v("七", "qī", "Thất", "Bảy (7)", "Số từ", "Mua sắm & Trả giá", "Bộ: 一 (Nhất)", "2 nét", "七天。", "Qī tiān.", "Bảy ngày."),
            v("八", "bā", "Bát", "Tám (8)", "Số từ", "Mua sắm & Trả giá", "Bộ: 八 (Bát)", "2 nét", "八个苹果。", "Bā gè píngguǒ.", "Tám quả táo."),
            v("九", "jiǔ", "Cửu", "Chín (9)", "Số từ", "Mua sắm & Trả giá", "Bộ: 丿 (Phiệt)", "2 nét", "九点半。", "Jiǔ diǎn bàn.", "Chín giờ rưỡi."),
            v("十", "shí", "Thập", "Mười (10)", "Số từ", "Mua sắm & Trả giá", "Bộ: 十 (Thập)", "2 nét", "十月份。", "Shí yuèfèn.", "Tháng mười."),
            v("百", "bǎi", "Bách", "Trăm (100)", "Số từ", "Mua sắm & Trả giá", "Bộ: 白 (Bạch)", "6 nét", "一百块钱。", "Yìbǎi kuài qián.", "Một trăm tệ."),
            v("千", "qiān", "Thiên", "Nghìn, ngàn (1.000)", "Số từ", "Mua sắm & Trả giá", "Bộ: 十 (Thập)", "3 nét", "一千个人。", "Yìqiān gè rén.", "Một nghìn người."),
            v("万", "wàn", "Vạn", "Vạn, mười nghìn (10.000)", "Số từ", "Mua sắm & Trả giá", "Bộ: 一 (Nhất)", "3 nét", "两万块。", "Liǎng wàn kuài.", "Hai vạn tệ (20.000 tệ)."),
            v("第一", "dì-yī", "Đệ Nhất", "Thứ nhất, đầu tiên", "Số từ", "Học tập & Giáo dục", "Bộ: 竹 (Trúc)", "12 nét", "他是第一名。", "Tā shì dì-yī míng.", "Cậu ấy đứng thứ nhất."),
            v("半", "bàn", "Bán", "Nửa, rưỡi (1/2)", "Số từ", "Thời gian & Ngày tháng", "Bộ: 十 (Thập)", "5 nét", "半个小时。", "Bàn gè xiǎoshí.", "Nửa tiếng đồng hồ."),

            // ── 3. LƯỢNG TỪ (MEASURE WORDS) ──
            v("个", "gè", "Cá", "Cái, con, người (thông dụng)", "Lượng từ", "Mua sắm & Trả giá", "Bộ: 人 (Nhân)", "3 nét", "这个手机很好用。", "Zhège shǒujī hěn hǎoyòng.", "Cái điện thoại này rất dễ dùng."),
            v("本", "běn", "Bản", "Cuốn, quyển (sách, vở)", "Lượng từ", "Học tập & Giáo dục", "Bộ: 木 (Mộc)", "5 nét", "我看了一本书。", "Wǒ kàn le yì běn shū.", "Tôi đã đọc một cuốn sách."),
            v("块", "kuài", "Khối", "Đồng, tệ (tiền) / Cục, miếng", "Lượng từ", "Mua sắm & Trả giá", "Bộ: 土 (Thổ)", "7 nét", "一块西瓜。", "Yí kuài xīguā.", "Một miếng dưa hấu."),
            v("只", "zhī", "Chích", "Con (động vật), chiếc (tay/chân)", "Lượng từ", "Động vật & Thiên nhiên", "Bộ: 口 (Khẩu)", "5 nét", "两只小狗。", "Liǎng zhī xiǎogǒu.", "Hai con chó nhỏ."),
            v("件", "jiàn", "Kiện", "Chiếc, cái (áo, sự việc)", "Lượng từ", "Trang phục & Thời trang", "Bộ: 亻 (Nhân)", "6 nét", "这件衣服很漂亮。", "Zhè jiàn yīfu hěn piàoliang.", "Chiếc áo này rất đẹp."),
            v("张", "zhāng", "Trương", "Tờ, tấm, bức (vé, bàn, giấy)", "Lượng từ", "Nhà cửa & Đồ dùng", "Bộ: 弓 (Cung)", "7 nét", "一张火车票。", "Yì zhāng huǒchē piào.", "Một chiếc vé tàu hỏa."),
            v("条", "tiáo", "Điều", "Con, chiếc, sợi (dài: cá, đường, quần)", "Lượng từ", "Ăn uống & Ẩm thực", "Bộ: 木 (Mộc)", "7 nét", "一条红裙子。", "Yì tiáo hóng qúnzi.", "Một chiếc váy đỏ."),
            v("杯", "bēi", "Bôi", "Cốc, ly (trà, nước, cà phê)", "Lượng từ", "Ăn uống & Ẩm thực", "Bộ: 木 (Mộc)", "8 nét", "请给我一杯水。", "Qǐng gěi wǒ yì bēi shuǐ.", "Làm ơn cho tôi một cốc nước."),
            v("瓶", "píng", "Bình", "Chai, lọ, bình", "Lượng từ", "Ăn uống & Ẩm thực", "Bộ: 瓦 (Ngõa)", "10 nét", "一瓶牛奶。", "Yì píng niúnǎi.", "Một chai sữa bò."),
            v("碗", "wǎn", "Oản", "Bát, chén (cơm, súp)", "Lượng từ", "Ăn uống & Ẩm thực", "Bộ: 石 (Thạch)", "13 nét", "我想吃一碗牛肉面。", "Wǒ xiǎng chī yì wǎn niúròumiàn.", "Tôi muốn ăn một bát mì bò."),
            v("位", "wèi", "Vị", "Vị, người (lịch sự: thầy giáo, khách)", "Lượng từ", "Chào hỏi & Giao tiếp", "Bộ: 亻 (Nhân)", "7 nét", "这位老师很好。", "Zhè wèi lǎoshī hěn hǎo.", "Vị giáo viên này rất tốt."),
            v("双", "shuāng", "Song", "Đôi (giày, đũa, mắt)", "Lượng từ", "Trang phục & Thời trang", "Bộ: 又 (Hựu)", "4 nét", "一双筷子。", "Yì shuāng kuàizi.", "Một đôi đũa."),
            v("辆", "liàng", "Lượng", "Chiếc, con (xe: ô tô, xe đạp)", "Lượng từ", "Đi lại & Du lịch", "Bộ: 车 (Xa)", "11 nét", "一辆出租车。", "Yí liàng chūzūchē.", "Một chiếc xe taxi."),
            v("斤", "jīn", "Cân", "Cân Trung Quốc (bằng 500g)", "Lượng từ", "Mua sắm & Trả giá", "Bộ: 斤 (Cân)", "4 nét", "苹果三块钱一斤。", "Píngguǒ sān kuài qián yì jīn.", "Táo ba tệ một cân (500g)."),
            v("点", "diǎn", "Điểm", "Giờ / Chút, ít", "Lượng từ", "Thời gian & Ngày tháng", "Bộ: 灬 (Hỏa)", "9 nét", "现在上午八点。", "Xiànzài shàngwǔ bā diǎn.", "Bây giờ là tám giờ sáng."),
            v("些", "xiē", "Tắc", "Một số, vài, những", "Lượng từ", "Mua sắm & Trả giá", "Bộ: 二 (Nhị)", "8 nét", "买这些苹果吧。", "Mǎi zhèxiē píngguǒ ba.", "Mua những quả táo này đi."),
            v("次", "cì", "Thứ", "Lần, lượt", "Lượng từ", "Học tập & Giáo dục", "Bộ: 欠 (Khiếm)", "6 nét", "我去过一次中国。", "Wǒ qù guo yí cì Zhōngguó.", "Tôi từng đi Trung Quốc một lần."),
            v("遍", "biàn", "Biến", "Lần, lượt (từ đầu đến cuối)", "Lượng từ", "Học tập & Giáo dục", "Bộ: 辶 (Sước)", "12 nét", "请再说一遍。", "Qǐng zài shuō yí biàn.", "Xin hãy nói lại một lần."),

            // ── 4. PHÓ TỪ (ADVERBS) ──
            v("不", "bù", "Bất", "Không, chẳng", "Phó từ", "Chào hỏi & Giao tiếp", "Bộ: 一 (Nhất)", "4 nét", "我不是老师。", "Wǒ bú shì lǎoshī.", "Tôi không phải là giáo viên."),
            v("没", "méi", "Một", "Không, chưa (có)", "Phó từ", "Chào hỏi & Giao tiếp", "Bộ: 氵 (Thủy)", "7 nét", "我没有钱。", "Wǒ méiyǒu qián.", "Tôi không có tiền."),
            v("很", "hěn", "Khẩn", "Rất, lắm", "Phó từ", "Chào hỏi & Giao tiếp", "Bộ: 彳 (Xích)", "9 nét", "汉语很有趣。", "Hànyǔ hěn yǒuqù.", "Tiếng Trung rất thú vị."),
            v("太", "tài", "Thái", "Quá, lắm", "Phó từ", "Cảm xúc & Tâm trạng", "Bộ: 大 (Đại)", "4 nét", "太好了！", "Tài hǎo le!", "Tốt quá rồi!"),
            v("都", "dōu", "Đô", "Đều, tất cả", "Phó từ", "Chào hỏi & Giao tiếp", "Bộ: 阝 (Ấp)", "10 nét", "我们都是好朋友。", "Wǒmen dōu shì hǎo péngyou.", "Chúng tôi đều là bạn tốt."),
            v("也", "yě", "Dã", "Cũng", "Phó từ", "Chào hỏi & Giao tiếp", "Bộ: 乙 (Ất)", "3 nét", "我也去学校。", "Wǒ yě qù xuéxiào.", "Tôi cũng đi đến trường."),
            v("真", "zhēn", "Chân", "Thật, thực sự", "Phó từ", "Cảm xúc & Tâm trạng", "Bộ: 目 (Mục)", "10 nét", "这里真漂亮！", "Zhèlǐ zhēn piàoliang!", "Nơi này thật đẹp!"),
            v("最", "zuì", "Tối", "Nhất (so sánh)", "Phó từ", "Cảm xúc & Tâm trạng", "Bộ: 曰 (Viết)", "12 nét", "我最喜欢喝茶。", "Wǒ zuì xǐhuan hē chá.", "Tôi thích uống trà nhất."),
            v("再", "zài", "Tái", "Lại, nữa (hành động tương lai)", "Phó từ", "Chào hỏi & Giao tiếp", "Bộ: 冂 (Quynh)", "6 nét", "明天再见！", "Míngtiān zàijiàn!", "Ngày mai gặp lại!"),
            v("又", "yòu", "Hựu", "Lại, vừa (hành động đã xảy ra)", "Phó từ", "Thời gian & Ngày tháng", "Bộ: 又 (Hựu)", "2 nét", "今天他又迟到了。", "Jīntiān tā yòu chídào le.", "Hôm nay anh ấy lại đi muộn rồi."),
            v("就", "jiù", "Tựu", "Thì, ngay, liền", "Phó từ", "Thời gian & Ngày tháng", "Bộ: 尢 (Uông)", "12 nét", "我现在就去。", "Wǒ xiànzài jiù qù.", "Tôi đi ngay bây giờ đây."),
            v("还", "hái", "Hoàn", "Còn, vẫn, thêm", "Phó từ", "Mua sắm & Trả giá", "Bộ: 辶 (Sước)", "7 nét", "我还要吃米饭。", "Wǒ hái yào chī mǐfàn.", "Tôi vẫn muốn ăn cơm."),
            v("一起", "yìqǐ", "Nhất Khởi", "Cùng nhau", "Phó từ", "Chào hỏi & Giao tiếp", "Bộ: 走 (Tẩu)", "11 nét", "我们一起吃午饭吧。", "Wǒmen yìqǐ chī wǔfàn ba.", "Chúng mình cùng đi ăn trưa nhé."),
            v("一共", "yígòng", "Nhất Cộng", "Tổng cộng, tất cả", "Phó từ", "Mua sắm & Trả giá", "Bộ: 八 (Bát)", "7 nét", "一共多少钱？", "Yígòng duōshao qián?", "Tổng cộng bao nhiêu tiền?"),
            v("已经", "yǐjīng", "Dĩ Kinh", "Đã, rồi", "Phó từ", "Thời gian & Ngày tháng", "Bộ: 纟 (Mịch)", "11 nét", "他已经回家了。", "Tā yǐjīng huíjiā le.", "Anh ấy đã về nhà rồi."),
            v("正在", "zhèngzài", "Chính Tại", "Đang (hành động diễn ra)", "Phó từ", "Thời gian & Ngày tháng", "Bộ: 止 (Chỉ)", "11 nét", "妈妈正在做饭。", "Māma zhèngzài zuòfàn.", "Mẹ đang nấu cơm."),
            v("一直", "yìzhí", "Nhất Trực", "Liên tục, suốt / Đi thẳng", "Phó từ", "Phương hướng & Vị trí", "Bộ: 目 (Mục)", "9 nét", "向前一直走。", "Xiàng qián yìzhí zǒu.", "Cứ đi thẳng về phía trước."),
            v("经常", "jīngcháng", "Kinh Thường", "Thường xuyên, hay", "Phó từ", "Thời gian & Ngày tháng", "Bộ: 巾 (Cân)", "19 nét", "我经常去图书馆。", "Wǒ jīngcháng qù túshūguǎn.", "Tôi thường xuyên đến thư viện."),
            v("常常", "chángcháng", "Thường Thường", "Thường, hay", "Phó từ", "Thời gian & Ngày tháng", "Bộ: 巾 (Cân)", "22 nét", "他常常看中国电影。", "Tā chángcháng kàn Zhōngguó diànyǐng.", "Anh ấy thường xem phim Trung Quốc."),
            v("马上", "mǎshàng", "Mã Thượng", "Ngay lập tức, liền", "Phó từ", "Thời gian & Ngày tháng", "Bộ: 马 (Mã)", "6 nét", "老师马上就来。", "Lǎoshī mǎshàng jiù lái.", "Giáo viên sẽ tới ngay bây giờ."),
            v("别", "bié", "Biệt", "Đừng, chớ", "Phó từ", "Chào hỏi & Giao tiếp", "Bộ: 刂 (Đao)", "7 nét", "别说话，请听课。", "Bié shuōhuà, qǐng tīngkè.", "Đừng nói chuyện, hãy nghe giảng."),
            v("一定", "yídìng", "Nhất Định", "Nhất định, chắc chắn", "Phó từ", "Cảm xúc & Tâm trạng", "Bộ: 宀 (Miên)", "9 nét", "明天我一定会来。", "Míngtiān wǒ yídìng huì lái.", "Ngày mai tôi nhất định sẽ tới."),
            v("先", "xiān", "Tiên", "Trước, đầu tiên", "Phó từ", "Thời gian & Ngày tháng", "Bộ: 儿 (Nhân)", "6 nét", "你先走，我等他。", "Nǐ xiān zǒu, wǒ děng tā.", "Bạn đi trước đi, tôi đợi anh ấy."),

            // ── 5. LIÊN TỪ & GIỚI TỪ (CONJUNCTIONS & PREPOSITIONS) ──
            v("和", "hé", "Hòa", "Và, cùng với", "Liên từ", "Chào hỏi & Giao tiếp", "Bộ: 口 (Khẩu)", "8 nét", "我和他是朋友。", "Wǒ hé tā shì péngyou.", "Tôi và cậu ấy là bạn bè."),
            v("跟", "gēn", "Căn", "Cùng, theo, với", "Giới từ", "Chào hỏi & Giao tiếp", "Bộ: 足 (Túc)", "13 nét", "请跟我读。", "Qǐng gēn wǒ dú.", "Xin hãy đọc theo tôi."),
            v("同", "tóng", "Đồng", "Cùng, với / Giống nhau", "Giới từ", "Học tập & Giáo dục", "Bộ: 口 (Khẩu)", "6 nét", "我同他一起去。", "Wǒ tóng tā yìqǐ qù.", "Tôi cùng anh ấy đi."),
            v("但是", "dànshì", "Đãn Thị", "Nhưng, tuy nhiên", "Liên từ", "Chào hỏi & Giao tiếp", "Bộ: 亻 (Nhân)", "16 nét", "汉语很难，但是很有趣。", "Hànyǔ hěn nán, dànshì hěn yǒuqù.", "Tiếng Hán rất khó, nhưng rất thú vị."),
            v("可是", "kěshì", "Khả Thị", "Nhưng, thế nhưng", "Liên từ", "Chào hỏi & Giao tiếp", "Bộ: 口 (Khẩu)", "14 nét", "我想去，可是没时间。", "Wǒ xiǎng qù, kěshì méi shíjiān.", "Tôi muốn đi, thế nhưng không có thời gian."),
            v("因为", "yīnwèi", "Nhân Vi", "Bởi vì, do", "Liên từ", "Học tập & Giáo dục", "Bộ: 囗 (Vi)", "10 nét", "因为下雨，所以没去。", "Yīnwèi xiàyǔ, suǒyǐ méi qù.", "Bởi vì trời mưa nên không đi."),
            v("所以", "suǒyǐ", "Sở Dĩ", "Cho nên, vì thế", "Liên từ", "Học tập & Giáo dục", "Bộ: 斤 (Cân)", "12 nét", "他生病了，所以休息。", "Tā shēngbìng le, suǒyǐ xiūxi.", "Anh ấy bị ốm, vì thế nghỉ ngơi."),
            v("如果", "rúguǒ", "Như Quả", "Nếu, nếu như", "Liên từ", "Học tập & Giáo dục", "Bộ: 女 (Nữ)", "14 nét", "如果有问题，请问我。", "Rúguǒ yǒu wèntí, qǐng wèn wǒ.", "Nếu như có câu hỏi, hãy hỏi tôi."),
            v("虽然", "suīrán", "Tuy Nhiên", "Tuy rằng, mặc dù", "Liên từ", "Học tập & Giáo dục", "Bộ: 虫 (Trùng)", "20 nét", "虽然累，但是高兴。", "Suīrán lèi, dànshì gāoxìng.", "Mặc dù mệt nhưng rất vui."),
            v("在", "zài", "Tại", "Ở, tại", "Giới từ / Động từ", "Phương hướng & Vị trí", "Bộ: 土 (Thổ)", "6 nét", "我在这里等你。", "Wǒ zài zhèlǐ děng nǐ.", "Tôi ở đây đợi bạn."),
            v("从", "cóng", "Tùng", "Từ (địa điểm, thời gian)", "Giới từ", "Phương hướng & Vị trí", "Bộ: 人 (Nhân)", "4 nét", "从北京到上海。", "Cóng Běijīng dào Shànghǎi.", "Từ Bắc Kinh đến Thượng Hải."),
            v("到", "dào", "Đáo", "Đến, tới", "Giới từ / Động từ", "Đi lại & Du lịch", "Bộ: 刂 (Đao)", "8 nét", "火车到了。", "Huǒchē dào le.", "Tàu hỏa đã đến rồi."),
            v("给", "gěi", "Cấp", "Cho, tặng / Cho ai làm gì", "Giới từ / Động từ", "Chào hỏi & Giao tiếp", "Bộ: 纟 (Mịch)", "9 nét", "我给你打电话。", "Wǒ gěi nǐ dǎ diànhuà.", "Tôi gọi điện thoại cho bạn."),
            v("对", "duì", "Đối", "Đối với, với / Đúng", "Giới từ / Tính từ", "Học tập & Giáo dục", "Bộ: 寸 (Thốn)", "5 nét", "你说得对。", "Nǐ shuō de duì.", "Bạn nói đúng rồi."),
            v("比", "bǐ", "Tỉ", "So với, hơn (so sánh)", "Giới từ", "Thời tiết & Khí hậu", "Bộ: 比 (Tỉ)", "4 nét", "今天比昨天冷。", "Jīntiān bǐ zuótiān lěng.", "Hôm nay lạnh hơn hôm qua."),
            v("向", "xiàng", "Hướng", "Hướng về, về phía", "Giới từ", "Phương hướng & Vị trí", "Bộ: 口 (Khẩu)", "6 nét", "向前看。", "Xiàng qián kàn.", "Nhìn về phía trước."),
            v("往", "wǎng", "Vãng", "Đi về, hướng về", "Giới từ", "Phương hướng & Vị trí", "Bộ: 彳 (Xích)", "8 nét", "往右拐。", "Wǎng yòu guǎi.", "Rẽ về phía bên phải."),
            v("离", "lí", "Ly", "Cách, xa (khoảng cách)", "Giới từ", "Phương hướng & Vị trí", "Bộ: 亠 (Đầu)", "11 nét", "我家离学校很近。", "Wǒ jiā lí xuéxiào hěn jìn.", "Nhà tôi cách trường học rất gần."),
            v("为", "wèi", "Vị", "Vì, cho (mục đích)", "Giới từ", "Chào hỏi & Giao tiếp", "Bộ: 丶 (Chủ)", "4 nét", "这是为你买的。", "Zhè shì wèi nǐ mǎi de.", "Cái này là mua cho bạn đấy."),

            // ── 6. TRỢ TỪ & THÁN TỪ (PARTICLES & INTERJECTIONS) ──
            v("的", "de", "Đích", "Của (sở hữu, bổ nghĩa)", "Trợ từ", "Chào hỏi & Giao tiếp", "Bộ: 白 (Bạch)", "8 nét", "这是我的手机。", "Zhè shì wǒ de shǒujī.", "Đây là điện thoại của tôi."),
            v("得", "de", "Đắc", "Được (nối động từ và trạng ngữ)", "Trợ từ", "Học tập & Giáo dục", "Bộ: 彳 (Xích)", "11 nét", "他说汉语说得很好。", "Tā shuō Hànyǔ shuō de hěn hǎo.", "Anh ấy nói tiếng Trung rất tốt."),
            v("地", "de", "Địa", "Một cách (nối phó từ và động từ)", "Trợ từ", "Học tập & Giáo dục", "Bộ: 土 (Thổ)", "6 nét", "高兴地说。", "Gāoxìng de shuō.", "Nói một cách vui vẻ."),
            v("了", "le", "Liễu", "Đã, rồi (hoàn thành/đổi trạng thái)", "Trợ từ", "Chào hỏi & Giao tiếp", "Bộ: 亅 (Quyết)", "2 nét", "我吃了两个包子。", "Wǒ chī le liǎng gè bāozi.", "Tôi đã ăn hai cái bánh bao."),
            v("吗", "ma", "Ma", "À, ư, không (câu hỏi Có/Không)", "Trợ từ", "Chào hỏi & Giao tiếp", "Bộ: 口 (Khẩu)", "6 nét", "你是中国人吗？", "Nǐ shì Zhōngguó rén ma?", "Bạn là người Trung Quốc phải không?"),
            v("呢", "ne", "Ni", "Thế, nhỉ, đang (câu hỏi tỉnh lược)", "Trợ từ", "Chào hỏi & Giao tiếp", "Bộ: 口 (Khẩu)", "8 nét", "我很好，你呢？", "Wǒ hěn hǎo, nǐ ne?", "Tôi rất khỏe, còn bạn thì sao?"),
            v("吧", "ba", "Ba", "Đi, nhé, nào (thương lượng, gợi ý)", "Trợ từ", "Chào hỏi & Giao tiếp", "Bộ: 口 (Khẩu)", "7 nét", "我们走吧！", "Wǒmen zǒu ba!", "Chúng mình đi thôi nào!"),
            v("啊", "a", "A", "A, ôi, chà (thán từ cảm thán)", "Trợ từ / Thán từ", "Cảm xúc & Tâm trạng", "Bộ: 口 (Khẩu)", "10 nét", "真好吃啊！", "Zhēn hǎochī a!", "Ngon thật đấy chà!"),
            v("喂", "wèi", "Uy", "A-lô (nghe điện thoại) / Này", "Thán từ", "Chào hỏi & Giao tiếp", "Bộ: 口 (Khẩu)", "12 nét", "喂，请问王老师在吗？", "Wèi, qǐngwèn Wáng lǎoshī zài ma?", "A-lô, xin hỏi thầy Vương có ở đó không?"),

            // ── 7. CON NGƯỜI & GIA ĐÌNH (PEOPLE & FAMILY) ──
            v("人", "rén", "Nhân", "Người", "Danh từ", "Gia đình & Đời sống", "Bộ: 人 (Nhân)", "2 nét", "中国有很多的人。", "Zhōngguó yǒu hěn duō de rén.", "Trung Quốc có rất nhiều người."),
            v("男人", "nánrén", "Nam Nhân", "Đàn ông, người nam", "Danh từ", "Gia đình & Đời sống", "Bộ: 田 (Điền)", "9 nét", "那个男人是谁？", "Nàge nánrén shì shéi?", "Người đàn ông đằng kia là ai?"),
            v("女人", "nǚrén", "Nữ Nhân", "Phụ nữ, người nữ", "Danh từ", "Gia đình & Đời sống", "Bộ: 女 (Nữ)", "5 nét", "那里的女人很漂亮。", "Nàlǐ de nǚrén hěn piàoliang.", "Phụ nữ ở đó rất đẹp."),
            v("孩子", "háizi", "Hài Tử", "Con, trẻ con, đứa trẻ", "Danh từ", "Gia đình & Đời sống", "Bộ: 子 (Tử)", "8 nét", "那个孩子很聪明。", "Nàge háizi hěn cōngmíng.", "Đứa trẻ đó rất thông minh."),
            v("男孩", "nánhái", "Nam Hài", "Bé trai, cậu bé", "Danh từ", "Gia đình & Đời sống", "Bộ: 田 (Điền)", "14 nét", "他是个好男孩。", "Tā shì gè hǎo nánhái.", "Cậu ấy là một cậu bé ngoan."),
            v("女孩", "nǚhái", "Nữ Hài", "Bé gái, cô bé", "Danh từ", "Gia đình & Đời sống", "Bộ: 女 (Nữ)", "10 nét", "那个小女孩在跳舞。", "Nàge xiǎonǚhái zài tiàowǔ.", "Bé gái đó đang múa."),
            v("爸爸", "bàba", "Ba Ba", "Bố, cha, ba", "Danh từ", "Gia đình & Đời sống", "Bộ: 父 (Phụ)", "8 nét", "我爸爸是医生。", "Wǒ bàba shì yīshēng.", "Bố tôi là bác sĩ."),
            v("妈妈", "māma", "Ma Ma", "Mẹ, má", "Danh từ", "Gia đình & Đời sống", "Bộ: 女 (Nữ)", "6 nét", "妈妈做的中国菜真好吃。", "Māma zuò de Zhōngguó cài zhēn hǎochī.", "Món ăn Trung Quốc mẹ làm ngon thật đấy."),
            v("父母", "fùmǔ", "Phụ Mẫu", "Bố mẹ, cha mẹ", "Danh từ", "Gia đình & Đời sống", "Bộ: 父 (Phụ)", "9 nét", "我爱我的父母。", "Wǒ ài wǒ de fùmǔ.", "Tôi yêu cha mẹ của tôi."),
            v("哥哥", "gēge", "Ca Ca", "Anh trai", "Danh từ", "Gia đình & Đời sống", "Bộ: 口 (Khẩu)", "10 nét", "我哥哥在大学学习。", "Wǒ gēge zài dàxué xuéxí.", "Anh trai tôi đang học đại học."),
            v("弟弟", "dìdi", "Đệ Đệ", "Em trai", "Danh từ", "Gia đình & Đời sống", "Bộ: 弓 (Cung)", "7 nét", "弟弟喜欢踢足球。", "Dìdi xǐhuan tī zúqiú.", "Em trai tôi thích đá bóng."),
            v("姐姐", "jiějie", "Tỷ Tỷ", "Chị gái", "Danh từ", "Gia đình & Đời sống", "Bộ: 女 (Nữ)", "8 nét", "姐姐在一家公司工作。", "Jiějie zài yì jiā gōngsī gōngzuò.", "Chị gái tôi làm việc ở một công ty."),
            v("妹妹", "mèimei", "Muội Muội", "Em gái", "Danh từ", "Gia đình & Đời sống", "Bộ: 女 (Nữ)", "8 nét", "妹妹今年五岁了。", "Mèimei jīnnián wǔ suì le.", "Em gái năm nay năm tuổi rồi."),
            v("儿子", "érzi", "Nhi Tử", "Con trai", "Danh từ", "Gia đình & Đời sống", "Bộ: 儿 (Nhân)", "5 nét", "他的儿子很懂事。", "Tā de érzi hěn dǒngshì.", "Con trai anh ấy rất hiểu chuyện."),
            v("女儿", "nǚ'ér", "Nữ Nhi", "Con gái", "Danh từ", "Gia đình & Đời sống", "Bộ: 女 (Nữ)", "5 nét", "我有两个可爱的女儿。", "Wǒ yǒu liǎng gè kě'ài de nǚ'ér.", "Tôi có hai người con gái đáng yêu."),
            v("爷爷", "yéye", "Gia Gia", "Ông nội", "Danh từ", "Gia đình & Đời sống", "Bộ: 父 (Phụ)", "13 nét", "爷爷每天早上散步。", "Yéye měitiān zǎoshang sànbù.", "Ông nội sáng nào cũng đi dạo."),
            v("奶奶", "nǎinai", "Nãi Nãi", "Bà nội", "Danh từ", "Gia đình & Đời sống", "Bộ: 女 (Nữ)", "10 nét", "奶奶身体很好。", "Nǎinai shēntǐ hěn hǎo.", "Sức khỏe của bà nội rất tốt."),
            v("朋友", "péngyou", "Bằng Hữu", "Bạn bè, người bạn", "Danh từ", "Chào hỏi & Giao tiếp", "Bộ: 月 (Nguyệt)", "12 nét", "有朋友自远方来。", "Yǒu péngyou zì yuǎnfāng lái.", "Có bạn bè từ nơi phương xa tới."),
            v("同学", "tóngxué", "Đồng Học", "Bạn học, bạn cùng lớp", "Danh từ", "Học tập & Giáo dục", "Bộ: 口 (Khẩu)", "14 nét", "李明是我的大学同学。", "Lǐ Míng shì wǒ de dàxué tóngxué.", "Lý Minh là bạn đại học của tôi."),
            v("老师", "lǎoshī", "Lão Sư", "Thầy giáo, cô giáo", "Danh từ", "Học tập & Giáo dục", "Bộ: 老 (Lão)", "12 nét", "王老师教我们发音。", "Wáng lǎoshī jiāo wǒmen fāyīn.", "Thầy Vương dạy chúng tôi phát âm."),
            v("学生", "xuésheng", "Học Sinh", "Học sinh, sinh viên", "Danh từ", "Học tập & Giáo dục", "Bộ: 子 (Tử)", "13 nét", "学校里有很多学生。", "Xuéxiào lǐ yǒu hěn duō xuésheng.", "Trong trường có rất nhiều học sinh."),
            v("医生", "yīshēng", "Y Sinh", "Bác sĩ", "Danh từ", "Sức khỏe & Y tế", "Bộ: 匚 (Phương)", "12 nét", "李医生非常认真负责。", "Lǐ yīshēng fēicháng rènzhēn fùzé.", "Bác sĩ Lý rất cẩn thận và có trách nhiệm."),
            v("护士", "hùshi", "Hộ Sĩ", "Y tá, điều dưỡng", "Danh từ", "Sức khỏe & Y tế", "Bộ: 扌 (Thủ)", "7 nét", "护士姐姐很温柔。", "Hùshi jiějie hěn wēnróu.", "Chị y tá rất dịu dàng."),
            v("司机", "sījī", "Ty Cơ", "Tài xế, người lái xe", "Danh từ", "Đi lại & Du lịch", "Bộ: 口 (Khẩu)", "11 nét", "出租车司机师傅。", "Chūzūchē sījī shīfu.", "Bác tài xế lái xe taxi."),
            v("服务员", "fúwùyuán", "Phục Vụ Viên", "Nhân viên phục vụ", "Danh từ", "Khách sạn & Lưu trú", "Bộ: 亻 (Nhân)", "20 nét", "服务员，请结账。", "Fúwùyuán, qǐng jiézhàng.", "Phục vụ ơi, làm ơn tính tiền."),
            v("先生", "xiānsheng", "Tiên Sinh", "Ông, ngài, quý ông / Chồng", "Danh từ", "Chào hỏi & Giao tiếp", "Bộ: 儿 (Nhân)", "11 nét", "张先生，您好！", "Zhāng xiānsheng, nín hǎo!", "Chào ông Trương ạ!"),
            v("女士", "nǚshì", "Nữ Sĩ", "Bà, cô, phu nhân (lịch sự)", "Danh từ", "Chào hỏi & Giao tiếp", "Bộ: 女 (Nữ)", "6 nét", "这位女士是谁？", "Zhè wèi nǚshì shì shéi?", "Vị quý bà này là ai vậy?"),
            v("小姐", "xiǎojiě", "Tiểu Thư", "Cô gái, tiểu thư", "Danh từ", "Chào hỏi & Giao tiếp", "Bộ: 小 (Tiểu)", "11 nét", "王小姐在看书。", "Wáng xiǎojiě zài kànshū.", "Cô Vương đang đọc sách."),
            v("叔叔", "shūshu", "Thúc Thúc", "Chú, bác trai", "Danh từ", "Gia đình & Đời sống", "Bộ: 又 (Hựu)", "16 nét", "叔叔好！", "Shūshu hǎo!", "Cháu chào chú ạ!"),
            v("阿姨", "āyí", "A Di", "Dì, cô, bác gái", "Danh từ", "Gia đình & Đời sống", "Bộ: 阝 (Phụ)", "16 nét", "阿姨给我买了一个苹果。", "Āyí gěi wǒ mǎi le yí gè píngguǒ.", "Dì đã mua cho tôi một quả táo."),
            v("邻居", "línjū", "Lân Cư", "Hàng xóm, láng giềng", "Danh từ", "Gia đình & Đời sống", "Bộ: 阝 (Ấp)", "15 nét", "我们和邻居关系很好。", "Wǒmen hé línjū guānxi hěn hǎo.", "Chúng tôi quan hệ rất tốt với hàng xóm."),
            v("客人", "kèrén", "Khách Nhân", "Khách, người khách", "Danh từ", "Chào hỏi & Giao tiếp", "Bộ: 宀 (Miên)", "11 nét", "家里来了很多客人。", "Jiā lǐ lái le hěn duō kèrén.", "Trong nhà có rất nhiều khách đến."),

            // ── 8. THỜI GIAN, NGÀY THÁNG, MÙA (TIME & DATES) ──
            v("年", "nián", "Niên", "Năm", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 干 (Can)", "6 nét", "我学汉语学了一年。", "Wǒ xué Hànyǔ xué le yì nián.", "Tôi học tiếng Trung được một năm rồi."),
            v("月", "yuè", "Nguyệt", "Tháng / Mặt trăng", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 月 (Nguyệt)", "4 nét", "下个月我去中国。", "Xià gè yuè wǒ qù Zhōngguó.", "Tháng sau tôi đi Trung Quốc."),
            v("日", "rì", "Nhật", "Ngày / Mặt trời (văn viết)", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 日 (Nhật)", "4 nét", "十月一日是国庆节。", "Shí yuè yī rì shì Guóqìngjié.", "Ngày 1 tháng 10 là ngày Quốc khánh."),
            v("号", "hào", "Hiệu", "Ngày (văn nói) / Số hiệu", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 口 (Khẩu)", "5 nét", "今天几号？", "Jīntiān jǐ hào?", "Hôm nay ngày mùng mấy?"),
            v("星期", "xīngqī", "Tinh Kỳ", "Tuần, thứ", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 日 (Nhật)", "21 nét", "星期日我们去公园。", "Xīngqīrì wǒmen qù gōngyuán.", "Chủ nhật chúng tôi đi công viên."),
            v("周", "zhōu", "Chu", "Tuần (chu kỳ)", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 口 (Khẩu)", "8 nét", "这周末你有空吗？", "Zhè zhōumò nǐ yǒu kòng ma?", "Cuối tuần này bạn rảnh không?"),
            v("天", "tiān", "Thiên", "Ngày / Trời", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 大 (Đại)", "4 nét", "这两天天天下雨。", "Zhè liǎng tiān tiāntiān xiàyǔ.", "Hai ngày nay trời mưa suốt ngày."),
            v("时间", "shíjiān", "Thời Gian", "Thời gian", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 日 (Nhật)", "11 nét", "你现在有时间吗？", "Nǐ xiànzài yǒu shíjiān ma?", "Bây giờ bạn có thời gian không?"),
            v("时候", "shíhou", "Thời Hậu", "Lúc, khi, thời điểm", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 日 (Nhật)", "14 nét", "我小时候喜欢游泳。", "Wǒ xiǎoshíhou xǐhuan yóuyǒng.", "Hồi bé tôi thích bơi lội."),
            v("现在", "xiànzài", "Hiện Tại", "Bây giờ, hiện tại", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 王 (Vương)", "14 nét", "现在是下午三点。", "Xiànzài shì xiàwǔ sān diǎn.", "Bây giờ là ba giờ chiều."),
            v("今天", "jīntiān", "Kim Thiên", "Hôm nay", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 人 (Nhân)", "8 nét", "今天天气非常好。", "Jīntiān tiānqì fēicháng hǎo.", "Hôm nay thời tiết cực kỳ đẹp."),
            v("明天", "míngtiān", "Minh Thiên", "Ngày mai", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 日 (Nhật)", "12 nét", "明天见，祝你一路平安！", "Míngtiān jiàn, zhù nǐ yílù píng'ān!", "Ngày mai gặp lại, chúc bạn thượng lộ bình an!"),
            v("昨天", "zuótiān", "Tạc Thiên", "Hôm qua", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 日 (Nhật)", "13 nét", "昨天你在哪儿？", "Zuótiān nǐ zài nǎr?", "Hôm qua bạn ở đâu thế?"),
            v("前天", "qiántiān", "Tiền Thiên", "Hôm kia", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 刂 (Đao)", "13 nét", "前天我买了一本书。", "Qiántiān wǒ mǎi le yì běn shū.", "Hôm kia tôi đã mua một cuốn sách."),
            v("后天", "hòutiān", "Hậu Thiên", "Ngày kìa, ngày mốt", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 口 (Khẩu)", "10 nét", "后天星期六。", "Hòutiān xīngqīliù.", "Ngày mốt là thứ bảy."),
            v("今年", "jīnnián", "Kim Niên", "Năm nay", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 人 (Nhân)", "10 nét", "今年我已经二十岁了。", "Jīnnián wǒ yǐjīng èrshí suì le.", "Năm nay tôi đã 20 tuổi rồi."),
            v("明年", "míngnián", "Minh Niên", "Năm sau, sang năm", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 日 (Nhật)", "14 nét", "明年我想去旅行。", "Míngnián wǒ xiǎng qù lǚxíng.", "Sang năm tôi muốn đi du lịch."),
            v("去年", "qùnián", "Khứ Niên", "Năm ngoái", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 厶 (Khứ)", "11 nét", "去年我去了北京。", "Qùnián wǒ qù le Běijīng.", "Năm ngoái tôi đã đi Bắc Kinh."),
            v("早上", "zǎoshang", "Tảo Thượng", "Buổi sáng (sớm)", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 日 (Nhật)", "9 nét", "早上好！", "Zǎoshang hǎo!", "Chào buổi sáng!"),
            v("上午", "shàngwǔ", "Thượng Ngọ", "Buổi sáng (trước 12h)", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 一 (Nhất)", "7 nét", "上午八点上课。", "Shàngwǔ bā diǎn shàngkè.", "Tám giờ sáng vào lớp."),
            v("中午", "zhōngwǔ", "Trung Ngọ", "Buổi trưa (11h-13h)", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 丨 (Cổn)", "8 nét", "中午吃什么？", "Zhōngwǔ chī shénme?", "Trưa nay ăn gì thế?"),
            v("下午", "xiàwǔ", "Hạ Ngọ", "Buổi chiều (sau 12h)", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 一 (Nhất)", "7 nét", "下午我们去打球。", "Xiàwǔ wǒmen qù dǎqiú.", "Chiều nay chúng mình đi chơi bóng."),
            v("晚上", "wǎnshang", "Vãn Thượng", "Buổi tối", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 日 (Nhật)", "14 nét", "晚上我在家看电视。", "Wǎnshang wǒ zài jiā kàn diànshì.", "Buổi tối tôi ở nhà xem tivi."),
            v("夜里", "yèlǐ", "Dạ Lý", "Đêm khuya, ban đêm", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 亠 (Đầu)", "15 nét", "夜里很安静。", "Yèlǐ hěn ānjìng.", "Ban đêm rất yên tĩnh."),
            v("小时", "xiǎoshí", "Tiểu Thời", "Tiếng, giờ đồng hồ", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 小 (Tiểu)", "10 nét", "等了两个小时。", "Děng le liǎng gè xiǎoshí.", "Đợi suốt hai tiếng đồng hồ."),
            v("分钟", "fēnzhōng", "Phân Chung", "Phút (thời lượng)", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 刀 (Đao)", "13 nét", "还有十分钟。", "Hái yǒu shí fēnzhōng.", "Còn mười phút nữa."),
            v("秒", "miǎo", "Miểu", "Giây (thời gian)", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 禾 (Hòa)", "9 nét", "一分有六十秒。", "Yì fēn yǒu liùshí miǎo.", "Một phút có 60 giây."),
            v("生日", "shēngrì", "Sinh Nhật", "Sinh nhật, ngày sinh", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 生 (Sinh)", "9 nét", "祝你生日快乐！", "Zhù nǐ shēngrì kuàilè!", "Chúc bạn sinh nhật vui vẻ!"),
            v("节日", "jiérì", "Tiết Nhật", "Ngày lễ, ngày tết", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 艹 (Thảo)", "9 nét", "春节是中国最大的节日。", "Chūnjié shì Zhōngguó zuì dà de jiérì.", "Tết Nguyên Đán là ngày lễ lớn nhất Trung Quốc."),
            v("春天", "chūntiān", "Xuân Thiên", "Mùa xuân", "Danh từ", "Thời tiết & Khí hậu", "Bộ: 日 (Nhật)", "13 nét", "春天花都开了。", "Chūntiān huā dōu kāi le.", "Mùa xuân hoa đều nở rồi."),
            v("夏天", "xiàtiān", "Hạ Thiên", "Mùa hè", "Danh từ", "Thời tiết & Khí hậu", "Bộ: 夂 (Trĩ)", "14 nét", "夏天天气很热。", "Xiàtiān tiānqì hěn rè.", "Mùa hè thời tiết rất nóng."),
            v("秋天", "qiūtiān", "Thu Thiên", "Mùa thu", "Danh từ", "Thời tiết & Khí hậu", "Bộ: 禾 (Hòa)", "13 nét", "北京的秋天最美。", "Běijīng de qiūtiān zuì měi.", "Mùa thu Bắc Kinh là đẹp nhất."),
            v("冬天", "dōngtiān", "Đông Thiên", "Mùa đông", "Danh từ", "Thời tiết & Khí hậu", "Bộ: 夂 (Trĩ)", "9 nét", "冬天会下雪。", "Dōngtiān huì xiàxuě.", "Mùa đông sẽ có tuyết rơi."),

            // ── 9. ĂN UỐNG & ẨM THỰC (FOOD & DRINK) ──
            v("吃", "chī", "Cật", "Ăn", "Động từ", "Ăn uống & Ẩm thực", "Bộ: 口 (Khẩu)", "6 nét", "你吃米饭还是面条？", "Nǐ chī mǐfàn háishi miàntiáo?", "Bạn ăn cơm hay ăn mì?"),
            v("喝", "hē", "Hát", "Uống", "Động từ", "Ăn uống & Ẩm thực", "Bộ: 口 (Khẩu)", "12 nét", "我想喝一杯温水。", "Wǒ xiǎng hē yì bēi wēnshuǐ.", "Tôi muốn uống một cốc nước ấm."),
            v("做饭", "zuòfàn", "Tác Phạn", "Nấu cơm, nấu ăn", "Động từ", "Ăn uống & Ẩm thực", "Bộ: 亻 (Nhân)", "18 nét", "爸爸在厨房做饭。", "Bàba zài chúfáng zuòfàn.", "Bố đang nấu cơm trong bếp."),
            v("菜", "cài", "Thái", "Món ăn, thức ăn / Rau củ", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 艹 (Thảo)", "11 nét", "中国人很喜欢喝中国茶。", "Zhōngguó rén hěn xǐhuan hē Zhōngguó chá.", "Người Trung Quốc rất thích uống trà Trung Hoa."),
            v("饭", "fàn", "Phạn", "Cơm, bữa ăn", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 饣 (Thực)", "7 nét", "我们去吃饭吧。", "Wǒmen qù chīfàn ba.", "Chúng mình đi ăn cơm đi."),
            v("米饭", "mǐfàn", "Mễ Phạn", "Cơm trắng", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 米 (Mễ)", "13 nét", "吃一碗米饭。", "Chī yì wǎn mǐfàn.", "Ăn một bát cơm trắng."),
            v("面条", "miàntiáo", "Diện Điều", "Mì sợi, bún mì", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 面 (Diện)", "16 nét", "他喜欢吃鸡蛋面条。", "Tā xǐhuan chī jīdàn miàntiáo.", "Anh ấy thích ăn mì sợi trứng gà."),
            v("包子", "bāozi", "Bao Tử", "Bánh bao", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 勹 (Bao)", "8 nét", "早上吃肉包子。", "Zǎoshang chī ròu bāozi.", "Buổi sáng ăn bánh bao thịt."),
            v("饺子", "jiǎozi", "Sủi Tử", "Bánh chẻo, sủi cảo", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 饣 (Thực)", "11 nét", "过年吃饺子。", "Guònián chī jiǎozi.", "Đón tết ăn sủi cảo."),
            v("面包", "miànbāo", "Diện Bao", "Bánh mì", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 面 (Diện)", "14 nét", "喝牛奶，吃面包。", "Hē niúnǎi, chī miànbāo.", "Uống sữa bò, ăn bánh mì."),
            v("肉", "ròu", "Nhục", "Thịt", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 肉 (Nhục)", "6 nét", "我不爱吃肥肉。", "Wǒ bú ài chī féiròu.", "Tôi không thích ăn thịt mỡ."),
            v("牛肉", "niúròu", "Ngưu Nhục", "Thịt bò", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 牛 (Ngưu)", "10 nét", "来一盘牛肉。", "Lái yì pán niúròu.", "Cho một đĩa thịt bò."),
            v("羊肉", "yángròu", "Dương Nhục", "Thịt cừu", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 羊 (Dương)", "12 nét", "冬天吃羊肉很暖和。", "Dōngtiān chī yángròu hěn nuǎnhuo.", "Mùa đông ăn thịt cừu rất ấm áp."),
            v("猪肉", "zhūròu", "Trư Nhục", "Thịt lợn, thịt heo", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 犭 (Khuyển)", "17 nét", "猪肉多少钱一斤？", "Zhūròu duōshao qián yì jīn?", "Thịt lợn bao nhiêu tiền một cân?"),
            v("鸡肉", "jīròu", "Kê Nhục", "Thịt gà", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 鸟 (Điểu)", "13 nét", "今天吃烤鸡肉。", "Jīntiān chī kǎojīròu.", "Hôm nay ăn thịt gà nướng."),
            v("鱼", "yú", "Ngư", "Cá", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 鱼 (Ngư)", "8 nét", "红烧鱼很好吃。", "Hóngshāoyú hěn hǎochī.", "Cá kho tàu rất ngon."),
            v("蛋", "dàn", "Đản", "Trứng", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 疋 (Thất)", "11 nét", "吃个煮蛋。", "Chī gè zhǔdàn.", "Ăn một quả trứng luộc."),
            v("鸡蛋", "jīdàn", "Kê Đản", "Trứng gà", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 鸟 (Điểu)", "18 nét", "西红柿炒鸡蛋。", "Xīhóngshì chǎo jīdàn.", "Cà chua xào trứng gà."),
            v("水果", "shuǐguǒ", "Thủy Quả", "Hoa quả, trái cây", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 水 (Thủy)", "12 nét", "多吃水果身体好。", "Duō chī shuǐguǒ shēntǐ hǎo.", "Ăn nhiều hoa quả tốt cho sức khỏe."),
            v("苹果", "píngguǒ", "Bình Quả", "Quả táo", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 艹 (Thảo)", "16 nét", "红苹果真甜。", "Hóng píngguǒ zhēn tián.", "Táo đỏ ngọt thật đấy."),
            v("香蕉", "xiāngjiāo", "Hương Tiêu", "Quả chuối", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 艹 (Thảo)", "21 nét", "买两斤香蕉。", "Mǎi liǎng jīn xiāngjiāo.", "Mua hai cân chuối."),
            v("西瓜", "xīguā", "Tây Qua", "Dưa hấu", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 瓜 (Qua)", "11 nét", "夏天吃冰西瓜。", "Xiàtiān chī bīng xīguā.", "Mùa hè ăn dưa hấu ướp lạnh."),
            v("蔬菜", "shūcài", "Sơ Thái", "Rau củ, rau xanh", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 艹 (Thảo)", "22 nét", "新鲜的蔬菜。", "Xīnxiān de shūcài.", "Rau củ tươi ngon."),
            v("白菜", "báicài", "Bạch Thái", "Rau cải thảo, bắp cải", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 白 (Bạch)", "16 nét", "大白菜很便宜。", "Dàbáicài hěn piányi.", "Bắp cải thảo rất rẻ."),
            v("水", "shuǐ", "Thủy", "Nước", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 水 (Thủy)", "4 nét", "喝点热水吧。", "Hē diǎn rèshuǐ ba.", "Uống chút nước nóng đi."),
            v("茶", "chá", "Trà", "Trà, chè", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 艹 (Thảo)", "9 nét", "你喜欢喝绿茶吗？", "Nǐ xǐhuan hē lǜchá ma?", "Bạn thích uống trà xanh không?"),
            v("咖啡", "kāfēi", "Cà Phê", "Cà phê", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 口 (Khẩu)", "16 nét", "早上一杯热咖啡。", "Zǎoshang yì bēi rè kāfēi.", "Buổi sáng một tách cà phê nóng."),
            v("牛奶", "niúnǎi", "Ngưu Nãi", "Sữa bò, sữa tươi", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 牛 (Ngưu)", "9 nét", "睡前喝一杯牛奶。", "Shuìqián hē yì bēi niúnǎi.", "Trước khi ngủ uống một ly sữa ấm."),
            v("果汁", "guǒzhī", "Quả Trấp", "Nước ép hoa quả", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 木 (Mộc)", "13 nét", "橙汁很好喝。", "Chéngzhī hěn hǎohē.", "Nước cam ép rất ngon."),
            v("汤", "tāng", "Thang", "Canh, súp", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 氵 (Thủy)", "6 nét", "喝一碗热鸡汤。", "Hē yì wǎn rè jītāng.", "Uống một bát canh gà nóng."),
            v("糖", "táng", "Đường", "Đường, kẹo", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 米 (Mễ)", "16 nét", "咖啡里少放点糖。", "Kāfēi lǐ shǎo fàng diǎn táng.", "Cho ít đường vào cà phê thôi nhé."),
            v("盐", "yán", "Diêm", "Muối ăn", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 皿 (Mãnh)", "11 nét", "菜里别放太多盐。", "Cài lǐ bié fàng tài duō yán.", "Món ăn đừng cho nhiều muối quá."),
            v("饱", "bǎo", "Bão", "No (bụng)", "Tính từ", "Ăn uống & Ẩm thực", "Bộ: 饣 (Thực)", "8 nét", "我已经吃饱了。", "Wǒ yǐjīng chī bǎo le.", "Tôi đã ăn no rồi."),
            v("饿", "è", "Ngạ", "Đói (bụng)", "Tính từ", "Ăn uống & Ẩm thực", "Bộ: 饣 (Thực)", "10 nét", "肚子饿了，去吃饭。", "Dùzi è le, qù chīfàn.", "Bụng đói rồi, đi ăn cơm thôi."),
            v("渴", "kě", "Khát", "Khát (nước)", "Tính từ", "Ăn uống & Ẩm thực", "Bộ: 氵 (Thủy)", "12 nét", "我很渴，想喝水。", "Wǒ hěn kě, xiǎng hē shuǐ.", "Tôi rất khát, muốn uống nước."),
            v("好吃", "hǎochī", "Hảo Cật", "Ngon (món ăn)", "Tính từ", "Ăn uống & Ẩm thực", "Bộ: 女 (Nữ)", "12 nét", "北京烤鸭很好吃。", "Běijīng kǎoyā hěn hǎochī.", "Vịt quay Bắc Kinh ăn rất ngon."),
            v("好喝", "hǎohē", "Hảo Hát", "Ngon (đồ uống)", "Tính từ", "Ăn uống & Ẩm thực", "Bộ: 女 (Nữ)", "18 nét", "这杯奶茶真好喝。", "Zhè bēi nǎichá zhēn hǎohē.", "Cốc trà sữa này uống ngon thật đấy."),
            v("味道", "wèidào", "Vị Đạo", "Mùi vị, hương vị", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 口 (Khẩu)", "16 nét", "这道菜的味道好极了。", "Zhè dào cài de wèidào hǎojíle.", "Hương vị của món ăn này tuyệt cú mèo."),

            // ── 10. PHƯƠNG HƯỚNG, VỊ TRÍ & ĐỊA ĐIỂM (DIRECTIONS & PLACES) ──
            v("上", "shàng", "Thượng", "Trên, lên / Vào (lớp, làm)", "Phương vị từ / Động từ", "Phương hướng & Vị trí", "Bộ: 一 (Nhất)", "3 nét", "桌子上有一本书。", "Zhuōzi shàng yǒu yì běn shū.", "Trên bàn có một cuốn sách."),
            v("下", "xià", "Hạ", "Dưới, xuống / Tan (lớp, làm)", "Phương vị từ / Động từ", "Phương hướng & Vị trí", "Bộ: 一 (Nhất)", "3 nét", "椅子下面有一只猫。", "Yǐzi xiàmiàn yǒu yì zhī māo.", "Dưới ghế có một con mèo."),
            v("前", "qián", "Tiền", "Trước", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 刂 (Đao)", "9 nét", "他在我前面走。", "Tā zài wǒ qiánmian zǒu.", "Anh ấy đi ở phía trước tôi."),
            v("前面", "qiánmian", "Tiền Diện", "Phía trước, đằng trước", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 刂 (Đao)", "18 nét", "前面就是医院。", "Qiánmian jiù shì yīyuàn.", "Phía trước chính là bệnh viện."),
            v("后", "hòu", "Hậu", "Sau", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 口 (Khẩu)", "6 nét", "五天后见。", "Wǔ tiān hòu jiàn.", "Năm ngày sau gặp lại."),
            v("后面", "hòumian", "Hậu Diện", "Phía sau, đằng sau", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 口 (Khẩu)", "15 nét", "商店在学校后面。", "Shāngdiàn zài xuéxiào hòumian.", "Cửa hàng nằm ở phía sau trường học."),
            v("左", "zuǒ", "Tả", "Trái, bên trái", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 工 (Công)", "5 nét", "向左看。", "Xiàng zuǒ kàn.", "Nhìn sang bên trái."),
            v("左边", "zuǒbian", "Tả Biên", "Phía bên trái", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 工 (Công)", "10 nét", "银行在左边。", "Yínháng zài zuǒbian.", "Ngân hàng nằm ở bên trái."),
            v("右", "yòu", "Hữu", "Phải, bên phải", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 口 (Khẩu)", "5 nét", "右手拿笔。", "Yòushǒu ná bǐ.", "Tay phải cầm bút."),
            v("右边", "yòubian", "Hữu Biên", "Phía bên phải", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 口 (Khẩu)", "10 nét", "右边是超市。", "Yòubian shì chāoshì.", "Bên phải là siêu thị."),
            v("里", "lǐ", "Lý", "Trong, bên trong", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 里 (Lý)", "7 nét", "书包里有手机。", "Shūbāo lǐ yǒu shǒujī.", "Trong cặp có điện thoại."),
            v("里面", "lǐmian", "Lý Diện", "Phía trong, đằng trong", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 里 (Lý)", "16 nét", "房间里面很暖和。", "Fángjiān lǐmian hěn nuǎnhuo.", "Bên trong phòng rất ấm áp."),
            v("外", "wài", "Ngoại", "Ngoài, bên ngoài", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 夕 (Tịch)", "5 nét", "门外有人。", "Mén wài yǒu rén.", "Ngoài cửa có người."),
            v("外面", "wàimian", "Ngoại Diện", "Phía ngoài, bên ngoài", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 夕 (Tịch)", "14 nét", "外面很冷，多穿点。", "Wàimian hěn lěng, duō chuān diǎn.", "Bên ngoài rất lạnh, mặc nhiều áo vào."),
            v("中间", "zhōngjiān", "Trung Gian", "Ở giữa", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 丨 (Cổn)", "11 nét", "我坐在他们中间。", "Wǒ zuò zài tāmen zhōngjiān.", "Tôi ngồi ở giữa bọn họ."),
            v("旁边", "pángbiān", "Bàng Biên", "Bên cạnh", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 方 (Phương)", "15 nét", "小狗睡在桌子旁边。", "Xiǎogǒu shuì zài zhuōzi pángbiān.", "Con chó nhỏ ngủ ở bên cạnh bàn."),
            v("对面", "duìmiàn", "Đối Diện", "Đối diện", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 寸 (Thốn)", "14 nét", "饭馆在学校对面。", "Fànguǎn zài xuéxiào duìmiàn.", "Quán ăn nằm ở đối diện trường học."),
            v("东", "dōng", "Đông", "Phía đông", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 一 (Nhất)", "5 nét", "太阳从东方升起。", "Tàiyáng cóng dōngfāng shēngqǐ.", "Mặt trời mọc từ phía đông."),
            v("南", "nán", "Nam", "Phía nam", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 十 (Thập)", "9 nét", "南方冬天不冷。", "Nánfāng dōngtiān bù lěng.", "Miền nam mùa đông không lạnh."),
            v("西", "xī", "Tây", "Phía tây", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 覀 (Á)", "6 nét", "西方文化。", "Xīfāng wénhuà.", "Văn hóa phương tây."),
            v("北", "běi", "Bắc", "Phía bắc", "Phương vị từ", "Phương hướng & Vị trí", "Bộ: 匕 (Chủy)", "5 nét", "北京在北方。", "Běijīng zài běifāng.", "Bắc Kinh ở phía bắc."),
            v("家", "jiā", "Gia", "Nhà, gia đình", "Danh từ", "Gia đình & Đời sống", "Bộ: 宀 (Miên)", "10 nét", "我家在北京。", "Wǒ jiā zài Běijīng.", "Nhà tôi ở Bắc Kinh."),
            v("学校", "xuéxiào", "Học Hiệu", "Trường học", "Danh từ", "Học tập & Giáo dục", "Bộ: 子 (Tử)", "16 nét", "我们的学校很大。", "Wǒmen de xuéxiào hěn dà.", "Trường học của chúng tôi rất to."),
            v("班", "bān", "Ban", "Lớp học / Ca làm", "Danh từ", "Học tập & Giáo dục", "Bộ: 王 (Vương)", "10 nét", "我们班有二十个学生。", "Wǒmen bān yǒu èrshí gè xuésheng.", "Lớp chúng tôi có 20 học sinh."),
            v("教室", "jiàoshì", "Giáo Thất", "Phòng học, lớp học", "Danh từ", "Học tập & Giáo dục", "Bộ: 攴 (Phác)", "20 nét", "请进教室上课。", "Qǐng jìn jiàoshì shàngkè.", "Xin mời vào phòng học để nghe giảng."),
            v("饭馆", "fànguǎn", "Phạn Quán", "Nhà hàng, quán ăn", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 饣 (Thực)", "19 nét", "这家饭馆的菜很好吃。", "Zhè jiā fànguǎn de cài hěn hǎochī.", "Món ăn ở quán ăn này rất ngon."),
            v("餐厅", "cāntīng", "Xan Thính", "Nhà ăn, phòng ăn", "Danh từ", "Ăn uống & Ẩm thực", "Bộ: 又 (Hựu)", "20 nét", "我们在学校餐厅吃饭。", "Wǒmen zài xuéxiào cāntīng chīfàn.", "Chúng tôi ăn cơm ở nhà ăn trường học."),
            v("商店", "shāngdiàn", "Thương Điếm", "Cửa hàng, tiệm", "Danh từ", "Mua sắm & Trả giá", "Bộ: 口 (Khẩu)", "19 nét", "去商店买水果。", "Qù shāngdiàn mǎi shuǐguǒ.", "Đi cửa hàng mua hoa quả."),
            v("超市", "chāoshì", "Siêu Thị", "Siêu thị", "Danh từ", "Mua sắm & Trả giá", "Bộ: 走 (Tẩu)", "17 nét", "超市里有很多便宜的东西。", "Chāoshì lǐ yǒu hěn duō piányi de dōngxi.", "Trong siêu thị có rất nhiều đồ rẻ."),
            v("医院", "yīyuàn", "Y Viện", "Bệnh viện", "Danh từ", "Sức khỏe & Y tế", "Bộ: 匚 (Phương)", "16 nét", "他在医院工作。", "Tā zài yīyuàn gōngzuò.", "Anh ấy làm việc ở bệnh viện."),
            v("药店", "yàodiàn", "Dược Điếm", "Hiệu thuốc, nhà thuốc", "Danh từ", "Sức khỏe & Y tế", "Bộ: 艹 (Thảo)", "17 nét", "去药店买感冒药。", "Qù yàodiàn mǎi gǎnmàoyào.", "Đi hiệu thuốc mua thuốc cảm cúm."),
            v("银行", "yínháng", "Ngân Hàng", "Ngân hàng", "Danh từ", "Ngân hàng & Tài chính", "Bộ: 钅 (Kim)", "17 nét", "我在银行换钱。", "Wǒ zài yínháng huànqián.", "Tôi đổi tiền ở ngân hàng."),
            v("机场", "jīchǎng", "Cơ Trường", "Sân bay", "Danh từ", "Đi lại & Du lịch", "Bộ: 木 (Mộc)", "12 nét", "在机场我们可以打出租车。", "Zài jīchǎng wǒmen kěyǐ dǎ chūzūchē.", "Ở sân bay chúng ta có thể bắt taxi."),
            v("车站", "chēzhàn", "Xa Trạm", "Bến xe, nhà ga", "Danh từ", "Đi lại & Du lịch", "Bộ: 车 (Xa)", "14 nét", "公共汽车站在前面。", "Gōnggòng qìchēzhàn zài qiánmian.", "Trạm xe buýt ở phía trước."),
            v("房间", "fángjiān", "Phòng Gian", "Phòng, căn phòng", "Danh từ", "Khách sạn & Lưu trú", "Bộ: 户 (Hộ)", "15 nét", "这个房间很干净。", "Zhè ge fángjiān hěn gānjìng.", "Căn phòng này rất sạch sẽ."),
            v("卫生间", "wèishēngjiān", "Vệ Sinh Gian", "Nhà vệ sinh, toilet", "Danh từ", "Khách sạn & Lưu trú", "Bộ: 卩 (Tiết)", "17 nét", "请问卫生间在哪里？", "Qǐngwèn wèishēngjiān zài nǎlǐ?", "Xin hỏi nhà vệ sinh ở đâu ạ?"),
            v("厨房", "chúfáng", "Trù Phòng", "Nhà bếp, gian bếp", "Danh từ", "Nhà cửa & Đồ dùng", "Bộ: 厂 (Hán)", "20 nét", "妈妈在厨房里做饭。", "Māma zài chúfáng lǐ zuòfàn.", "Mẹ đang nấu cơm trong bếp."),
            v("门口", "ménkǒu", "Môn Khẩu", "Cổng, lối ra vào", "Danh từ", "Phương hướng & Vị trí", "Bộ: 门 (Môn)", "6 nét", "我在学校门口等你。", "Wǒ zài xuéxiào ménkǒu děng nǐ.", "Tôi đợi bạn ở cổng trường học."),
            v("路上", "lùshang", "Lộ Thượng", "Trên đường", "Danh từ", "Đi lại & Du lịch", "Bộ: 足 (Túc)", "14 nét", "路上车很多，要小心。", "Lùshang chē hěn duō, yào xiǎoxīn.", "Trên đường xe rất đông, phải cẩn thận."),
            v("北京", "Běijīng", "Bắc Kinh", "Bắc Kinh (thủ đô TQ)", "Danh từ riêng", "Đi lại & Du lịch", "Bộ: 匕 (Chủy)", "13 nét", "我爱北京天安门。", "Wǒ ài Běijīng Tiān'ānmén.", "Tôi yêu Thiên An Môn Bắc Kinh."),
            v("中国", "Zhōngguó", "Trung Quốc", "Trung Quốc", "Danh từ riêng", "Đi lại & Du lịch", "Bộ: 丨 (Cổn)", "12 nét", "我在中国学习汉语。", "Wǒ zài Zhōngguó xuéxí Hànyǔ.", "Tôi đang học tiếng Trung ở Trung Quốc."),
            v("外国", "wàiguó", "Ngoại Quốc", "Nước ngoài", "Danh từ", "Đi lại & Du lịch", "Bộ: 夕 (Tịch)", "13 nét", "他是外国留学生。", "Tā shì wàiguó liúxuéshēng.", "Anh ấy là lưu học sinh nước ngoài."),

            // ── 11. ĐI LẠI & DU LỊCH (TRAVEL & TRANSPORT) ──
            v("去", "qù", "Khứ", "Đi, đến", "Động từ", "Đi lại & Du lịch", "Bộ: 厶 (Khứ)", "5 nét", "你明天去哪儿旅游？", "Nǐ míngtiān qù nǎr lǚyóu?", "Ngày mai bạn đi đâu du lịch?"),
            v("来", "lái", "Lai", "Đến, tới", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 木 (Mộc)", "7 nét", "老师向我们走来。", "Lǎoshī xiàng wǒmen zǒulái.", "Thầy giáo đang đi về phía chúng tôi."),
            v("回", "huí", "Hồi", "Về, quay lại", "Động từ", "Gia đình & Đời sống", "Bộ: 囗 (Vi)", "6 nét", "我下午四点回家。", "Wǒ xiàwǔ sì diǎn huíjiā.", "Bốn giờ chiều tôi về nhà."),
            v("走", "zǒu", "Tẩu", "Đi, bước đi", "Động từ", "Đi lại & Du lịch", "Bộ: 走 (Tẩu)", "7 nét", "时间不早了，我们走吧。", "Shíjiān bù zǎo le, wǒmen zǒu ba.", "Thời gian không còn sớm nữa, chúng mình đi thôi."),
            v("跑", "pǎo", "Bào", "Chạy", "Động từ", "Thể thao & Vận động", "Bộ: 足 (Túc)", "12 nét", "小狗在草地上跑。", "Xiǎogǒu zài cǎodì shàng pǎo.", "Con chó nhỏ chạy trên bãi cỏ."),
            v("坐", "zuò", "Tọa", "Ngồi / Đi (xe, tàu, máy bay)", "Động từ", "Đi lại & Du lịch", "Bộ: 土 (Thổ)", "7 nét", "我们坐飞机去北京。", "Wǒmen zuò fēijī qù Běijīng.", "Chúng tôi đi máy bay đến Bắc Kinh."),
            v("站", "zhàn", "Trạm", "Đứng / Trạm, ga xe", "Động từ / Danh từ", "Đi lại & Du lịch", "Bộ: 立 (Lập)", "10 nét", "请站起来回答问题。", "Qǐng zhàn qǐlái huídá wèntí.", "Xin hãy đứng dậy trả lời câu hỏi."),
            v("骑", "qí", "Kỵ", "Cưỡi, đạp (xe, ngựa)", "Động từ", "Đi lại & Du lịch", "Bộ: 马 (Mã)", "11 nét", "我骑自行车去学校。", "Wǒ qí zìxíngchē qù xuéxiào.", "Tôi đạp xe đạp đi đến trường."),
            v("开", "kāi", "Khai", "Mở, bật / Lái (xe)", "Động từ", "Đi lại & Du lịch", "Bộ: 廾 (Củng)", "4 nét", "爸爸在开车。", "Bàba zài kāichē.", "Bố đang lái xe ô tô."),
            v("飞", "fēi", "Phi", "Bay", "Động từ", "Đi lại & Du lịch", "Bộ: 飞 (Phi)", "3 nét", "小鸟在天上飞。", "Xiǎoniǎo zài tiān shàng fēi.", "Con chim nhỏ bay trên trời."),
            v("飞机", "fēijī", "Phi Cơ", "Máy bay", "Danh từ", "Đi lại & Du lịch", "Bộ: 飞 (Phi)", "9 nét", "坐飞机去上海要两小时。", "Zuò fēijī qù Shànghǎi yào liǎng xiǎoshí.", "Đi máy bay đến Thượng Hải mất hai tiếng."),
            v("火车", "huǒchē", "Hỏa Xa", "Tàu hỏa, xe lửa", "Danh từ", "Đi lại & Du lịch", "Bộ: 火 (Hỏa)", "8 nét", "我们坐火车去旅行。", "Wǒmen zuò huǒchē qù lǚxíng.", "Chúng tôi đi tàu hỏa đi du lịch."),
            v("地铁", "dìtiě", "Địa Thiết", "Tàu điện ngầm", "Danh từ", "Đi lại & Du lịch", "Bộ: 土 (Thổ)", "16 nét", "北京的地铁很方便。", "Běijīng de dìtiě hěn fāngbiàn.", "Tàu điện ngầm Bắc Kinh rất tiện lợi."),
            v("出租车", "chūzūchē", "Xuất Tô Xa", "Xe taxi", "Danh từ", "Đi lại & Du lịch", "Bộ: 刀 (Đao)", "19 nét", "我们在路边打出租车。", "Wǒmen zài lùbiān dǎ chūzūchē.", "Chúng tôi vẫy xe taxi ở ven đường."),
            v("公共汽车", "gōnggòng qìchē", "Công Cộng Khí Xa", "Xe buýt", "Danh từ", "Đi lại & Du lịch", "Bộ: 八 (Bát)", "20 nét", "我每天坐公共汽车上班。", "Wǒ měitiān zuò gōnggòng qìchē shàngbān.", "Mỗi ngày tôi đều đi xe buýt đi làm."),
            v("自行车", "zìxíngchē", "Tự Hành Xa", "Xe đạp", "Danh từ", "Đi lại & Du lịch", "Bộ: 自 (Tự)", "16 nét", "这是一辆新自行车。", "Zhè shì yí liàng xīn zìxíngchē.", "Đây là một chiếc xe đạp mới."),
            v("船", "chuán", "Thuyền", "Thuyền, tàu thủy", "Danh từ", "Đi lại & Du lịch", "Bộ: 舟 (Chu)", "11 nét", "坐船看风景。", "Zuò chuán kàn fēngjǐng.", "Đi thuyền ngắm phong cảnh."),
            v("票", "piào", "Phiếu", "Vé (xe, tàu, xem phim)", "Danh từ", "Đi lại & Du lịch", "Bộ: 示 (Thị)", "11 nét", "请拿出您的车票。", "Qǐng náchū nín de chēpiào.", "Xin hãy xuất trình vé xe của ngài."),
            v("路", "lù", "Lộ", "Đường đi, con đường / Tuyến xe", "Danh từ", "Đi lại & Du lịch", "Bộ: 足 (Túc)", "13 nét", "这条路很宽。", "Zhè tiáo lù hěn kuān.", "Con đường này rất rộng."),
            v("旅游", "lǚyóu", "Lữ Du", "Du lịch, đi chơi", "Động từ / Danh từ", "Đi lại & Du lịch", "Bộ: 方 (Phương)", "22 nét", "下个月我们去北京旅游。", "Xià gè yuè wǒmen qù Běijīng lǚyóu.", "Tháng sau chúng tôi đi Bắc Kinh du lịch."),
            v("出发", "chūfā", "Xuất Phát", "Xuất phát, khởi hành", "Động từ", "Đi lại & Du lịch", "Bộ: 凵 (Khảm)", "10 nét", "我们明天早上七点出发。", "Wǒmen míngtiān zǎoshang qī diǎn chūfā.", "Chúng ta sáng mai bảy giờ xuất phát."),
            v("迟到", "chídào", "Trì Đáo", "Đến muộn, trễ giờ", "Động từ", "Học tập & Giáo dục", "Bộ: 辶 (Sước)", "15 nét", "上课不要迟到。", "Shàngkè bú yào chídào.", "Đi học đừng có đến muộn nhé.")
        )
    }
}
