package com.lumina.backend.config

import com.lumina.backend.model.entity.Vocabulary

/**
 * Danh mục 504 từ vựng chuẩn HSK 1 (Phần 2: Từ 253 đến 504)
 * Chuẩn khung HSK 3.0 Band 1 (Căn bản)
 */
object Hsk1DataPart2 {

    private fun v(
        hanzi: String, pinyin: String, hanViet: String, meaning: String,
        partOfSpeech: String, topic: String, radical: String, strokes: String,
        exHz: String, exPy: String, exM: String
    ): Vocabulary = Vocabulary(
        hanzi = hanzi, pinyin = pinyin, hanViet = hanViet, meaning = meaning,
        partOfSpeech = partOfSpeech, topic = topic, radical = radical, strokes = strokes,
        exampleHanzi = exHz, examplePinyin = exPy, exampleMeaning = exM,
        hskLevel = "HSK 1", targetScore = "HSK 1 (Mục tiêu 180–200/200 điểm)"
    )

    val words: List<Vocabulary> by lazy {
        listOf(
            // ── 12. HỌC TẬP & CÔNG VIỆC (EDUCATION & WORK) ──
            v("学", "xué", "Học", "Học", "Động từ", "Học tập & Giáo dục", "Bộ: 子 (Tử)", "8 nét", "我想学汉语。", "Wǒ xiǎng xué Hànyǔ.", "Tôi muốn học tiếng Trung."),
            v("学习", "xuéxí", "Học Tập", "Học tập, rèn luyện", "Động từ", "Học tập & Giáo dục", "Bộ: 子 (Tử)", "11 nét", "我们每天努力学习汉语。", "Wǒmen měitiān nǔlì xuéxí Hànyǔ.", "Chúng tôi mỗi ngày đều nỗ lực học tiếng Trung."),
            v("读", "dú", "Độc", "Đọc", "Động từ", "Học tập & Giáo dục", "Bộ: 讠 (Ngôn)", "10 nét", "请大声读课文。", "Qǐng dàshēng dú kèwén.", "Xin hãy đọc to bài khóa."),
            v("写", "xiě", "Tả", "Viết", "Động từ", "Học tập & Giáo dục", "Bộ: 冖 (Mịch)", "5 nét", "你在写什么？", "Nǐ zài xiě shénme?", "Bạn đang viết gì thế?"),
            v("字", "zì", "Tự", "Chữ, chữ Hán", "Danh từ", "Học tập & Giáo dục", "Bộ: 子 (Tử)", "6 nét", "这个字怎么读？", "Zhège zì zěnme dú?", "Chữ này đọc thế nào?"),
            v("听", "tīng", "Thính", "Nghe", "Động từ", "Học tập & Giáo dục", "Bộ: 口 (Khẩu)", "7 nét", "你在听什么音乐？", "Nǐ zài tīng shénme yīnyuè?", "Bạn đang nghe nhạc gì thế?"),
            v("说", "shuō", "Thuyết", "Nói", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 讠 (Ngôn)", "9 nét", "你会说汉语吗？", "Nǐ huì shuō Hànyǔ ma?", "Bạn biết nói tiếng Trung không?"),
            v("问", "wèn", "Vấn", "Hỏi", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 门 (Môn)", "6 nét", "我想问一个问题。", "Wǒ xiǎng wèn yí gè wèntí.", "Tôi muốn hỏi một câu hỏi."),
            v("回答", "huídá", "Hồi Đáp", "Trả lời", "Động từ", "Học tập & Giáo dục", "Bộ: 囗 (Vi)", "18 nét", "请回答我的问题。", "Qǐng huídá wǒ de wèntí.", "Xin hãy trả lời câu hỏi của tôi."),
            v("考", "kǎo", "Khảo", "Thi, kiểm tra", "Động từ", "Học tập & Giáo dục", "Bộ: 耂 (Lão)", "6 nét", "明天我们要考听力。", "Míngtiān wǒmen yào kǎo tīnglì.", "Ngày mai chúng tôi phải thi nghe."),
            v("考试", "kǎoshì", "Khảo Thí", "Kỳ thi, cuộc thi", "Danh từ / Động từ", "Học tập & Giáo dục", "Bộ: 耂 (Lão)", "14 nét", "下个星期有HSK考试。", "Xià gè xīngqī yǒu HSK kǎoshì.", "Tuần sau có kỳ thi HSK."),
            v("懂", "dǒng", "Hiểu", "Hiểu, nắm rõ", "Động từ", "Học tập & Giáo dục", "Bộ: 忄 (Tâm)", "15 nét", "这句话你懂了吗？", "Zhè jù huà nǐ dǒng le ma?", "Câu này bạn đã hiểu chưa?"),
            v("知道", "zhīdào", "Tri Đạo", "Biết", "Động từ", "Học tập & Giáo dục", "Bộ: 矢 (Thỉ)", "20 nét", "我知道他的电话号码。", "Wǒ zhīdào tā de diànhuà hàomǎ.", "Tôi biết số điện thoại của anh ấy."),
            v("明白", "míngbai", "Minh Bạch", "Hiểu rõ, sáng tỏ", "Động từ / Tính từ", "Học tập & Giáo dục", "Bộ: 日 (Nhật)", "13 nét", "我明白老师的意思了。", "Wǒ míngbai lǎoshī de yìsi le.", "Tôi hiểu rõ ý của thầy giáo rồi."),
            v("认识", "rènshi", "Nhận Thức", "Quen biết, nhận ra", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 讠 (Ngôn)", "12 nét", "认识你很高兴！", "Rènshí nǐ hěn gāoxìng!", "Rất vui được làm quen với bạn!"),
            v("记住", "jìzhù", "Ký Trú", "Ghi nhớ, nhớ kỹ", "Động từ", "Học tập & Giáo dục", "Bộ: 讠 (Ngôn)", "12 nét", "要记住这十个生词。", "Yào jìzhù zhè shí gè shēngcí.", "Cần phải nhớ kỹ 10 từ mới này."),
            v("汉语", "Hànyǔ", "Hán Ngữ", "Tiếng Trung, tiếng Hán", "Danh từ", "Học tập & Giáo dục", "Bộ: 氵 (Thủy)", "14 nét", "汉语很有意思。", "Hànyǔ hěn yǒuyìsi.", "Tiếng Trung rất thú vị."),
            v("中文", "Zhōngwén", "Trung Văn", "Tiếng Trung (văn tự)", "Danh từ", "Học tập & Giáo dục", "Bộ: 丨 (Cổn)", "8 nét", "桌子上有一本中文书。", "Zhuōzi shàng yǒu yì běn Zhōngwén shū.", "Trên bàn có một cuốn sách tiếng Trung."),
            v("英语", "Yīngyǔ", "Anh Ngữ", "Tiếng Anh", "Danh từ", "Học tập & Giáo dục", "Bộ: 艹 (Thảo)", "17 nét", "他会说英语和汉语。", "Tā huì shuō Yīngyǔ hé Hànyǔ.", "Anh ấy biết nói cả tiếng Anh và tiếng Trung."),
            v("课", "kè", "Khóa", "Tiết học, bài học", "Danh từ", "Học tập & Giáo dục", "Bộ: 讠 (Ngôn)", "10 nét", "今天我们学第五课。", "Jīntiān wǒmen xué dì-wǔ kè.", "Hôm nay chúng ta học bài số 5."),
            v("上课", "shàngkè", "Thượng Khóa", "Vào lớp, lên lớp", "Động từ", "Học tập & Giáo dục", "Bộ: 一 (Nhất)", "13 nét", "快点，马上要上课了。", "Kuài diǎn, mǎshàng yào shàngkè le.", "Nhanh lên, sắp vào lớp rồi."),
            v("下课", "xiàkè", "Hạ Khóa", "Tan học, tan lớp", "Động từ", "Học tập & Giáo dục", "Bộ: 一 (Nhất)", "13 nét", "下课后我们去打球。", "Xiàkè hòu wǒmen qù dǎqiú.", "Sau khi tan học chúng mình đi chơi bóng."),
            v("练习", "liànxí", "Luyện Tập", "Luyện tập, bài tập", "Động từ / Danh từ", "Học tập & Giáo dục", "Bộ: 纟 (Mịch)", "11 nét", "多做听力练习。", "Duō zuò tīnglì liànxí.", "Làm nhiều bài tập luyện nghe vào."),
            v("作业", "zuòyè", "Tác Nghiệp", "Bài tập về nhà", "Danh từ", "Học tập & Giáo dục", "Bộ: 亻 (Nhân)", "12 nét", "今天的作业做完了吗？", "Jīntiān de zuòyè zuòwán le ma?", "Bài tập hôm nay đã làm xong chưa?"),
            v("问题", "wèntí", "Vấn Đề", "Câu hỏi, vấn đề", "Danh từ", "Học tập & Giáo dục", "Bộ: 门 (Môn)", "24 nét", "这个问题很难回答。", "Zhège wèntí hěn nán huídá.", "Câu hỏi này rất khó trả lời."),
            v("书", "shū", "Thư", "Sách", "Danh từ", "Học tập & Giáo dục", "Bộ: 乛 (Ất)", "4 nét", "桌子上有一本书。", "Zhuōzi shàng yǒu yì běn shū.", "Trên bàn có một cuốn sách."),
            v("本子", "běnzi", "Bản Tử", "Quyển vở, cuốn sổ", "Danh từ", "Học tập & Giáo dục", "Bộ: 木 (Mộc)", "8 nét", "买两个笔记本。", "Mǎi liǎng gè bǐjìběn.", "Mua hai quyển vở ghi chép."),
            v("笔", "bǐ", "Bút", "Cây bút, bút viết", "Danh từ", "Học tập & Giáo dục", "Bộ: 竹 (Trúc)", "10 nét", "请借我一支笔。", "Qǐng jiè wǒ yì zhī bǐ.", "Làm ơn cho tôi mượn một cây bút."),
            v("字典", "zìdiǎn", "Tự Điển", "Từ điển", "Danh từ", "Học tập & Giáo dục", "Bộ: 子 (Tử)", "14 nét", "查字典学汉语。", "Chá zìdiǎn xué Hànyǔ.", "Tra từ điển để học tiếng Trung."),
            v("电脑", "diànnǎo", "Điện Não", "Máy vi tính", "Danh từ", "Công nghệ & Internet", "Bộ: 电 (Điện)", "16 nét", "他在电脑前工作。", "Tā zài diànnǎo qián gōngzuò.", "Anh ấy làm việc trước máy tính."),
            v("手机", "shǒujī", "Thủ Cơ", "Điện thoại di động", "Danh từ", "Công nghệ & Internet", "Bộ: 手 (Thủ)", "10 nét", "我用手机听录音。", "Wǒ yòng shǒujī tīng lùyīn.", "Tôi dùng điện thoại nghe băng ghi âm."),
            v("电话", "diànhuà", "Điện Thoại", "Điện thoại", "Danh từ", "Công nghệ & Internet", "Bộ: 电 (Điện)", "13 nét", "打一个电话。", "Dǎ yí gè diànhuà.", "Gọi một cuộc điện thoại."),
            v("打电话", "dǎ diànhuà", "Đả Điện Thoại", "Gọi điện thoại", "Động từ", "Công nghệ & Internet", "Bộ: 扌 (Thủ)", "18 nét", "妈妈正在给我打电话。", "Māma zhèngzài gěi wǒ dǎ diànhuà.", "Mẹ đang gọi điện thoại cho tôi."),
            v("工作", "gōngzuò", "Công Tác", "Làm việc, công việc", "Động từ / Danh từ", "Công việc & Công sở", "Bộ: 工 (Công)", "9 nét", "他在医院工作。", "Tā zài yīyuàn gōngzuò.", "Anh ấy làm việc ở bệnh viện."),
            v("上班", "shàngbān", "Thượng Ban", "Đi làm", "Động từ", "Công việc & Công sở", "Bộ: 一 (Nhất)", "13 nét", "爸爸每天早上八点上班。", "Bàba měitiān zǎoshang bā diǎn shàngbān.", "Bố tôi mỗi sáng tám giờ đi làm."),
            v("下班", "xiàbān", "Hạ Ban", "Tan làm, tan sở", "Động từ", "Công việc & Công sở", "Bộ: 一 (Nhất)", "13 nét", "今天下午五点半下班。", "Jīntiān xiàwǔ wǔ diǎn bàn xiàbān.", "Chiều nay 5 giờ rưỡi tan làm."),
            v("开会", "kāihuì", "Khai Hội", "Họp, mở cuộc họp", "Động từ", "Công việc & Công sở", "Bộ: 廾 (Củng)", "10 nét", "我们正在开会。", "Wǒmen zhèngzài kāihuì.", "Chúng tôi đang họp."),
            v("事情", "shìqing", "Sự Tình", "Sự việc, việc", "Danh từ", "Công việc & Công sở", "Bộ: 亅 (Quyết)", "19 nét", "今天有很多事情要做。", "Jīntiān yǒu hěn duō shìqing yào zuò.", "Hôm nay có rất nhiều việc phải làm."),
            v("办", "bàn", "Biện", "Làm, giải quyết", "Động từ", "Công việc & Công sở", "Bộ: 力 (Lực)", "4 nét", "怎么办？", "Zěnme bàn?", "Làm thế nào bây giờ?"),
            v("帮忙", "bāngmáng", "Bang Mang", "Giúp đỡ, giúp một tay", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 巾 (Cân)", "12 nét", "谢谢你的帮忙。", "Xièxie nǐ de bāngmáng.", "Cảm ơn sự giúp đỡ của bạn."),

            // ── 13. ĐỒ VẬT, NHÀ CỬA & ĐỜI SỐNG (OBJECTS & HOME) ──
            v("桌子", "zhuōzi", "Trác Tử", "Cái bàn", "Danh từ", "Nhà cửa & Đồ dùng", "Bộ: 木 (Mộc)", "13 nét", "桌子上有一本书。", "Zhuōzi shàng yǒu yì běn shū.", "Trên bàn có một cuốn sách."),
            v("椅子", "yǐzi", "Ỷ Tử", "Cái ghế", "Danh từ", "Nhà cửa & Đồ dùng", "Bộ: 木 (Mộc)", "15 nét", "请坐在椅子上。", "Qǐng zuò zài yǐzi shàng.", "Xin mời ngồi lên ghế."),
            v("床", "chuáng", "Sàng", "Cái giường", "Danh từ", "Nhà cửa & Đồ dùng", "Bộ: 广 (Quảng)", "7 nét", "房间里有一张大床。", "Fángjiān lǐ yǒu yì zhāng dà chuáng.", "Trong phòng có một chiếc giường lớn."),
            v("门", "mén", "Môn", "Cánh cửa, cửa", "Danh từ", "Nhà cửa & Đồ dùng", "Bộ: 门 (Môn)", "3 nét", "请开一下门。", "Qǐng kāi yíxià mén.", "Làm ơn mở cửa giúp tôi với."),
            v("窗户", "chuānghu", "Song Hộ", "Cửa sổ", "Danh từ", "Nhà cửa & Đồ dùng", "Bộ: 穴 (Huyệt)", "16 nét", "外面冷，请关上窗户。", "Wàimian lěng, qǐng guānshang chuānghu.", "Bên ngoài lạnh, xin hãy đóng cửa sổ lại."),
            v("灯", "dēng", "Đăng", "Cái đèn", "Danh từ", "Nhà cửa & Đồ dùng", "Bộ: 火 (Hỏa)", "6 nét", "天黑了，开灯吧。", "Tiān hēi le, kāidēng ba.", "Trời tối rồi, bật đèn lên thôi."),
            v("电视", "diànshì", "Điện Thị", "Tivi, vô tuyến", "Danh từ", "Giải trí & Sở thích", "Bộ: 电 (Điện)", "13 nét", "我和妈妈一起看电视。", "Wǒ hé māma yìqǐ kàn diànshì.", "Tôi cùng mẹ xem tivi."),
            v("电影", "diànyǐng", "Điện Ảnh", "Phim, điện ảnh", "Danh từ", "Giải trí & Sở thích", "Bộ: 电 (Điện)", "20 nét", "今晚我们去看电影吧。", "Jīnwǎn wǒmen qù kàn diànyǐng ba.", "Tối nay chúng mình đi xem phim nhé."),
            v("东西", "dōngxi", "Đông Tây", "Đồ vật, thứ, đồ đạc", "Danh từ", "Số đếm & Mua sắm", "Bộ: 一 (Nhất)", "11 nét", "这个东西多少钱？", "Zhège dōngxi duōshao qián?", "Cái đồ này bao nhiêu tiền?"),
            v("包", "bāo", "Bao", "Túi xách, bao, cặp", "Danh từ", "Trang phục & Thời trang", "Bộ: 勹 (Bao)", "5 nét", "书包在桌子下面。", "Shūbāo zài zhuōzi xiàmiàn.", "Cặp sách ở dưới gầm bàn."),
            v("表", "biǎo", "Biểu", "Đồng hồ / Bảng biểu", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 衣 (Y)", "8 nét", "看一下表，几点了？", "Kàn yíxià biǎo, jǐ diǎn le?", "Xem đồng hồ một chút, mấy giờ rồi?"),
            v("手表", "shǒubiǎo", "Thủ Biểu", "Đồng hồ đeo tay", "Danh từ", "Thời gian & Ngày tháng", "Bộ: 手 (Thủ)", "12 nét", "这块手表真漂亮。", "Zhè kuài shǒubiǎo zhēn piàoliang.", "Chiếc đồng hồ đeo tay này thật đẹp."),
            v("衣服", "yīfu", "Y Phục", "Quần áo", "Danh từ", "Trang phục & Thời trang", "Bộ: 衣 (Y)", "14 nét", "这件衣服挺便宜的。", "Zhè jiàn yīfu tǐng piányi de.", "Chiếc áo này khá là rẻ."),
            v("裤子", "kùzi", "Khố Tử", "Cái quần", "Danh từ", "Trang phục & Thời trang", "Bộ: 衤 (Y)", "15 nét", "我穿一条黑裤子。", "Wǒ chuān yì tiáo hēi kùzi.", "Tôi mặc một chiếc quần màu đen."),
            v("裙子", "qúnzi", "Quần Tử", "Cái váy, chân váy", "Danh từ", "Trang phục & Thời trang", "Bộ: 衤 (Y)", "15 nét", "这条白裙子真好看。", "Zhè tiáo bái qúnzi zhēn hǎokàn.", "Chiếc váy trắng này đẹp thật đấy."),
            v("鞋", "xié", "Hài", "Đôi giày", "Danh từ", "Trang phục & Thời trang", "Bộ: 革 (Cách)", "15 nét", "一双运动鞋。", "Yì shuāng yùndòngxié.", "Một đôi giày thể thao."),
            v("帽子", "màozi", "Mạo Tử", "Cái mũ, cái nón", "Danh từ", "Trang phục & Thời trang", "Bộ: 巾 (Cân)", "14 nét", "冬天出门要戴帽子。", "Dōngtiān chūmén yào dài màozi.", "Mùa đông ra ngoài cần đội mũ."),
            v("钱", "qián", "Tiền", "Tiền bạc", "Danh từ", "Ngân hàng & Tài chính", "Bộ: 钅 (Kim)", "10 nét", "我带的钱不够买这个。", "Wǒ dài de qián bú gòu mǎi zhège.", "Tiền tôi mang không đủ mua cái này."),
            v("人民币", "rénmínbì", "Nhân Dân Tệ", "Đồng Nhân dân tệ (RMB)", "Danh từ", "Ngân hàng & Tài chính", "Bộ: 人 (Nhân)", "9 nét", "一百元人民币。", "Yìbǎi yuán rénmínbì.", "Một trăm đồng nhân dân tệ."),
            v("元", "yuán", "Nguyên", "Đồng tệ (đơn vị chính thức)", "Lượng từ / Danh từ", "Số đếm & Mua sắm", "Bộ: 二 (Nhị)", "4 nét", "这本书十五元。", "Zhè běn shū shíwǔ yuán.", "Cuốn sách này 15 tệ."),
            v("角", "jiǎo", "Giác", "Hào (1/10 tệ, văn viết)", "Lượng từ", "Số đếm & Mua sắm", "Bộ: 角 (Giác)", "7 nét", "五角钱。", "Wǔ jiǎo qián.", "Năm hào."),
            v("毛", "máo", "Mao", "Hào (1/10 tệ, văn nói)", "Lượng từ", "Số đếm & Mua sắm", "Bộ: 毛 (Mao)", "4 nét", "两块五毛。", "Liǎng kuài wǔ máo.", "Hai tệ năm hào."),
            v("分", "fēn", "Phân", "Xu (1/100 tệ) / Điểm số", "Lượng từ / Danh từ", "Số đếm & Mua sắm", "Bộ: 刀 (Đao)", "4 nét", "考了一百分。", "Kǎo le yìbǎi fēn.", "Thi được 100 điểm."),
            v("纸", "zhǐ", "Chỉ", "Tờ giấy, giấy", "Danh từ", "Học tập & Giáo dục", "Bộ: 纟 (Mịch)", "7 nét", "拿一张白纸写字。", "Ná yì zhāng báizhǐ xiězì.", "Lấy một tờ giấy trắng viết chữ."),
            v("信", "xìn", "Tín", "Lá thư, bức thư / Tin tưởng", "Danh từ / Động từ", "Chào hỏi & Giao tiếp", "Bộ: 亻 (Nhân)", "9 nét", "我给妈妈写了一封信。", "Wǒ gěi māma xiě le yì fēng xìn.", "Tôi đã viết cho mẹ một bức thư."),
            v("照片", "zhàopiàn", "Chiếu Phiến", "Bức ảnh, tấm hình", "Danh từ", "Giải trí & Sở thích", "Bộ: 灬 (Hỏa)", "17 nét", "看，这是我们全家的照片。", "Kàn, zhè shì wǒmen quánjiā de zhàopiàn.", "Xem kìa, đây là ảnh cả nhà chúng tôi."),
            v("礼物", "lǐwù", "Lễ Vật", "Món quà, quà tặng", "Danh từ", "Chào hỏi & Giao tiếp", "Bộ: 礻 (Thị)", "13 nét", "谢谢你送我的生日礼物。", "Xièxie nǐ sòng wǒ de shēngrì lǐwù.", "Cảm ơn món quà sinh nhật bạn tặng tôi."),
            v("雨伞", "yǔsǎn", "Vũ Tản", "Cái ô, cây dù che mưa", "Danh từ", "Thời tiết & Khí hậu", "Bộ: 雨 (Vũ)", "20 nét", "下雨了，出门带雨伞。", "Xiàyǔ le, chūmén dài yǔsǎn.", "Mưa rồi, ra ngoài nhớ mang ô theo."),
            v("钥匙", "yàoshi", "Thược Thi", "Chìa khóa", "Danh từ", "Nhà cửa & Đồ dùng", "Bộ: 钅 (Kim)", "20 nét", "我把钥匙忘在家里了。", "Wǒ bǎ yàoshi wàng zài jiā lǐ le.", "Tôi để quên chìa khóa ở nhà rồi."),

            // ── 14. CƠ THỂ & SỨC KHỎE (BODY & HEALTH) ──
            v("身体", "shēntǐ", "Thân Thể", "Thân thể, sức khỏe", "Danh từ", "Sức khỏe & Y tế", "Bộ: 身 (Thân)", "14 nét", "祝你身体健康！", "Zhù nǐ shēntǐ jiànkāng!", "Chúc bạn sức khỏe dồi dào!"),
            v("头", "tóu", "Đầu", "Cái đầu", "Danh từ", "Sức khỏe & Y tế", "Bộ: 大 (Đại)", "5 nét", "我的头有点儿疼。", "Wǒ de tóu yǒudiǎnr téng.", "Đầu tôi hơi đau một chút."),
            v("头发", "tóufa", "Đầu Phát", "Tóc, mái tóc", "Danh từ", "Sức khỏe & Y tế", "Bộ: 大 (Đại)", "10 nét", "她的头发很长。", "Tā de tóufa hěn cháng.", "Tóc của cô ấy rất dài."),
            v("脸", "liǎn", "Kiểm", "Gương mặt, khuôn mặt", "Danh từ", "Sức khỏe & Y tế", "Bộ: 月 (Nguyệt)", "15 nét", "洗洗脸，精神好。", "Xǐxǐ liǎn, jīngshén hǎo.", "Rửa mặt đi cho tỉnh táo."),
            v("眼睛", "yǎnjing", "Nhãn Tinh", "Mắt, đôi mắt", "Danh từ", "Sức khỏe & Y tế", "Bộ: 目 (Mục)", "22 nét", "她的眼睛又大又亮。", "Tā de yǎnjing yòu dà yòu liàng.", "Đôi mắt của cô ấy vừa to vừa sáng."),
            v("耳朵", "ěrduo", "Nhĩ Đóa", "Tai, lỗ tai", "Danh từ", "Sức khỏe & Y tế", "Bộ: 耳 (Nhĩ)", "12 nét", "小兔子的耳朵长长的。", "Xiǎotùzi de ěrduo chángcháng de.", "Tai thỏ con dài dài."),
            v("鼻子", "bízi", "Tị Tử", "Cái mũi", "Danh từ", "Sức khỏe & Y tế", "Bộ: 鼻 (Tị)", "17 nét", "高高的小鼻子。", "Gāogāo de xiǎobízi.", "Chiếc mũi nhỏ cao cao."),
            v("嘴", "zuǐ", "Chủy", "Miệng, mồm", "Danh từ", "Sức khỏe & Y tế", "Bộ: 口 (Khẩu)", "16 nét", "张开嘴巴看医生。", "Zhāngkāi zuǐba kàn yīshēng.", "Há miệng ra để bác sĩ khám."),
            v("手", "shǒu", "Thủ", "Bàn tay, tay", "Danh từ", "Sức khỏe & Y tế", "Bộ: 手 (Thủ)", "4 nét", "饭前要洗手。", "Fànqián yào xǐshǒu.", "Trước khi ăn cơm phải rửa tay."),
            v("脚", "jiǎo", "Cước", "Bàn chân, chân", "Danh từ", "Sức khỏe & Y tế", "Bộ: 月 (Nguyệt)", "15 nét", "走了很长的路，脚很酸。", "Zǒu le hěn cháng de lù, jiǎo hěn suān.", "Đi đoạn đường dài mỏi hết cả chân."),
            v("腿", "tuǐ", "Thối", "Đôi chân, bắp đùi", "Danh từ", "Sức khỏe & Y tế", "Bộ: 月 (Nguyệt)", "15 nét", "踢足球踢伤了腿。", "Tī zúqiú tī shāng le tuǐ.", "Đá bóng bị thương vào chân."),
            v("病", "bìng", "Bệnh", "Bệnh tật, ốm đau", "Danh từ / Động từ", "Sức khỏe & Y tế", "Bộ: 疒 (Nạch)", "10 nét", "他生病了，不能来上课。", "Tā shēngbìng le, bù néng lái shàngkè.", "Cậu ấy ốm rồi, không thể đi học được."),
            v("看病", "kànbìng", "Khán Bệnh", "Khám bệnh, đi khám", "Động từ", "Sức khỏe & Y tế", "Bộ: 目 (Mục)", "14 nét", "明天去医院看病。", "Míngtiān qù yīyuàn kànbìng.", "Ngày mai đi bệnh viện khám bệnh."),
            v("感冒", "gǎnmào", "Cảm Mạo", "Cảm cúm, bị cảm", "Động từ / Danh từ", "Sức khỏe & Y tế", "Bộ: 心 (Tâm)", "21 nét", "我感冒了，流鼻涕。", "Wǒ gǎnmào le, liú bítì.", "Tôi bị cảm cúm rồi, chảy nước mũi."),
            v("发烧", "fāshāo", "Phát Thiêu", "Sốt, lên cơn sốt", "Động từ", "Sức khỏe & Y tế", "Bộ: 癶 (Bát)", "15 nét", "孩子发烧三十九度。", "Háizi fāshāo sānshíjiǔ dù.", "Đứa bé bị sốt 39 độ."),
            v("疼", "téng", "Đông", "Đau, đau nhức", "Tính từ", "Sức khỏe & Y tế", "Bộ: 疒 (Nạch)", "10 nét", "肚子很疼。", "Dùzi hěn téng.", "Bụng rất đau."),
            v("药", "yào", "Dược", "Thuốc uống", "Danh từ", "Sức khỏe & Y tế", "Bộ: 艹 (Thảo)", "10 nét", "记得按时吃药多喝水。", "Jìde ànshí chī yào duō hē shuǐ.", "Nhớ uống thuốc đúng giờ và uống nhiều nước."),
            v("吃药", "chīyào", "Cật Dược", "Uống thuốc", "Động từ", "Sức khỏe & Y tế", "Bộ: 口 (Khẩu)", "16 nét", "吃药后感觉好多了。", "Chī yào hòu gǎnjué hǎoduō le.", "Uống thuốc xong cảm thấy đỡ hơn nhiều rồi."),
            v("舒服", "shūfu", "Thư Phục", "Dễ chịu, thoải mái / Khỏe mạnh", "Tính từ", "Sức khỏe & Y tế", "Bộ: 舌 (Thiệt)", "16 nét", "今天我身体不太舒服。", "Jīntiān wǒ shēntǐ bú tài shūfu.", "Hôm nay người tôi không được khỏe lắm."),
            v("累", "lèi", "Luy", "Mệt mỏi, mệt", "Tính từ", "Sức khỏe & Y tế", "Bộ: 糸 (Mịch)", "11 nét", "今天上班真累。", "Jīntiān shàngbān zhēn lèi.", "Hôm nay đi làm thật là mệt mỏi."),
            v("休息", "xiūxi", "Hưu Tức", "Nghỉ ngơi", "Động từ", "Sức khỏe & Y tế", "Bộ: 亻 (Nhân)", "16 nét", "累了就坐下休息会儿。", "Lèi le jiù zuòxià xiūxi huìr.", "Mệt rồi thì ngồi xuống nghỉ ngơi một chút."),
            v("睡觉", "shuìjiào", "Thụy Giác", "Đi ngủ", "Động từ", "Gia đình & Đời sống", "Bộ: 目 (Mục)", "20 nét", "晚上十点准时睡觉。", "Wǎnshang shí diǎn zhǔnshí shuìjiào.", "Buổi tối đúng 10 giờ đi ngủ."),
            v("起床", "qǐchuáng", "Khởi Sàng", "Thức dậy, ngủ dậy", "Động từ", "Gia đình & Đời sống", "Bộ: 走 (Tẩu)", "14 nét", "明天早上六点起床。", "Míngtiān zǎoshang liù diǎn qǐchuáng.", "Sáng mai sáu giờ thức dậy."),

            // ── 15. ĐỘNG VẬT, THỰC VẬT & THIÊN NHIÊN (ANIMALS & NATURE) ──
            v("动物", "dòngwù", "Động Vật", "Động vật, con vật", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 力 (Lực)", "15 nét", "动物园里有很多动物。", "Dòngwùyuán lǐ yǒu hěn duō dòngwù.", "Trong sở thú có rất nhiều động vật."),
            v("狗", "gǒu", "Cẩu", "Con chó", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 犭 (Khuyển)", "8 nét", "我家养了一只可爱的小狗。", "Wǒ jiā yǎng le yì zhī kě'ài de xiǎogǒu.", "Nhà tôi nuôi một chú cún con rất đáng yêu."),
            v("猫", "māo", "Miêu", "Con mèo", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 犭 (Khuyển)", "11 nét", "黑猫白猫抓住老鼠就是好猫。", "Hēi māo bái māo zhuāzhù lǎoshǔ jiù shì hǎo māo.", "Mèo đen hay mèo trắng bắt được chuột đều là mèo tốt."),
            v("小猫", "xiǎomāo", "Tiểu Miêu", "Mèo con, mèo nhỏ", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 小 (Tiểu)", "14 nét", "小猫在睡觉。", "Xiǎomāo zài shuìjiào.", "Mèo con đang ngủ."),
            v("小狗", "xiǎogǒu", "Tiểu Cẩu", "Chó con, cún con", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 小 (Tiểu)", "11 nét", "那只小狗在跑。", "Nà zhī xiǎogǒu zài pǎo.", "Con cún con kia đang chạy."),
            v("鸟", "niǎo", "Điểu", "Con chim", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 鸟 (Điểu)", "5 nét", "树上有很多小鸟。", "Shù shàng yǒu hěn duō xiǎoniǎo.", "Trên cây có rất nhiều chú chim nhỏ."),
            v("马", "mǎ", "Mã", "Con ngựa", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 马 (Mã)", "3 nét", "草原上有很多白马。", "Cǎoyuán shang yǒu hěn duō bái mǎ.", "Trên thảo nguyên có rất nhiều ngựa trắng."),
            v("牛", "niú", "Ngưu", "Con bò", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 牛 (Ngưu)", "4 nét", "小牛在吃草。", "Xiǎoniú zài chī cǎo.", "Bê con đang gặm cỏ."),
            v("羊", "yáng", "Dương", "Con cừu, con dê", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 羊 (Dương)", "6 nét", "山坡上有一群羊。", "Shānpō shang yǒu yì qún yáng.", "Trên sườn núi có một đàn cừu."),
            v("鸡", "jī", "Kê", "Con gà", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 又 (Hựu)", "7 nét", "公鸡叫了，天亮了。", "Gōngjī jiào le, tiān liàng le.", "Gà trống gáy rồi, trời sáng rồi."),
            v("花", "huā", "Hoa", "Bông hoa, hoa", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 艹 (Thảo)", "7 nét", "春天红花开了。", "Chūntiān hóng huā kāi le.", "Mùa xuân hoa đỏ nở rộ."),
            v("草", "cǎo", "Thảo", "Cỏ, cây cỏ", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 艹 (Thảo)", "9 nét", "绿绿的青草。", "Lǜlǜ de qīngcǎo.", "Thảm cỏ xanh mướt."),
            v("树", "shù", "Thụ", "Cây cối, cái cây", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 木 (Mộc)", "9 nét", "大树底下好乘凉。", "Dà shù dǐxia hǎo chéngliáng.", "Dưới bóng cây to hóng mát thật tốt."),
            v("太阳", "tàiyáng", "Thái Dương", "Mặt trời", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 大 (Đại)", "10 nét", "今天的太阳真大。", "Jīntiān de tàiyáng zhēn dà.", "Hôm nay mặt trời to quá."),
            v("月亮", "yuèliang", "Nguyệt Lượng", "Mặt trăng", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 月 (Nguyệt)", "13 nét", "今晚的月亮很圆。", "Jīnwǎn de yuèliang hěn yuán.", "Mặt trăng tối nay rất tròn."),
            v("山", "shān", "Sơn", "Ngọn núi, núi", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 山 (Sơn)", "3 nét", "北京有很多美丽的山。", "Běijīng yǒu hěn duō měilì de shān.", "Bắc Kinh có rất nhiều ngọn núi đẹp."),
            v("河", "hé", "Hà", "Dòng sông, con sông", "Danh từ", "Động vật & Thiên nhiên", "Bộ: 氵 (Thủy)", "8 nét", "河水很清澈。", "Héshuǐ hěn qīngchè.", "Nước sông rất trong vắt."),
            v("风", "fēng", "Phong", "Cơn gió, gió", "Danh từ", "Thời tiết & Khí hậu", "Bộ: 风 (Phong)", "4 nét", "今天刮大风。", "Jīntiān guā dàfēng.", "Hôm nay gió thổi rất to."),
            v("雨", "yǔ", "Vũ", "Mưa", "Danh từ", "Thời tiết & Khí hậu", "Bộ: 雨 (Vũ)", "8 nét", "今天下大雨。", "Jīntiān xià dàyǔ.", "Hôm nay trời đổ mưa to."),
            v("雪", "xuě", "Tuyết", "Tuyết rơi", "Danh từ", "Thời tiết & Khí hậu", "Bộ: 雨 (Vũ)", "11 nét", "白雪像一幅画。", "Báixuě xiàng yì fú huà.", "Tuyết trắng tựa như một bức tranh."),

            // ── 16. THỜI TIẾT, MÀU SẮC & TÍNH TỪ (WEATHER, COLORS & ADJECTIVES) ──
            v("天气", "tiānqì", "Thiên Khí", "Thời tiết", "Danh từ", "Thời tiết & Khí hậu", "Bộ: 大 (Đại)", "8 nét", "今天天气真好。", "Jīntiān tiānqì zhēn hǎo.", "Hôm nay thời tiết thật là đẹp."),
            v("晴", "qíng", "Tình", "Trời nắng, tạnh ráo", "Tính từ", "Thời tiết & Khí hậu", "Bộ: 日 (Nhật)", "12 nét", "明天是个晴天。", "Míngtiān shì gè qíngtiān.", "Ngày mai là một ngày trời nắng đẹp."),
            v("阴", "yīn", "Âm", "Trời râm, u ám", "Tính từ", "Thời tiết & Khí hậu", "Bộ: 阝 (Phụ)", "6 nét", "今天阴天，可能下雨。", "Jīntiān yīntiān, kěnéng xiàyǔ.", "Hôm nay trời âm u, có thể sẽ mưa."),
            v("下雨", "xiàyǔ", "Hạ Vũ", "Trời mưa", "Động từ", "Thời tiết & Khí hậu", "Bộ: 一 (Nhất)", "11 nét", "外面下雨了，出门带伞。", "Wàimian xiàyǔ le, chūmén dài sǎn.", "Bên ngoài trời mưa rồi, ra ngoài nhớ mang ô."),
            v("下雪", "xiàxuě", "Hạ Tuyết", "Tuyết rơi", "Động từ", "Thời tiết & Khí hậu", "Bộ: 一 (Nhất)", "14 nét", "北京冬天经常下雪。", "Běijīng dōngtiān jīngcháng xiàxuě.", "Mùa đông Bắc Kinh thường có tuyết rơi."),
            v("冷", "lěng", "Lãnh", "Lạnh, buốt", "Tính từ", "Thời tiết & Khí hậu", "Bộ: 冫 (Băng)", "7 nét", "今天很冷，多穿衣服。", "Jīntiān hěn lěng, duō chuān yīfu.", "Hôm nay rất lạnh, mặc nhiều quần áo vào."),
            v("热", "rè", "Nhiệt", "Nóng, oi bức", "Tính từ", "Thời tiết & Khí hậu", "Bộ: 灬 (Hỏa)", "10 nét", "夏天天气很热。", "Xiàtiān tiānqì hěn rè.", "Mùa hè thời tiết rất nóng."),
            v("暖和", "nuǎnhuo", "Noãn Hòa", "Ấm áp", "Tính từ", "Thời tiết & Khí hậu", "Bộ: 日 (Nhật)", "21 nét", "春天来了，天气暖和了。", "Chūntiān lái le, tiānqì nuǎnhuo le.", "Mùa xuân đến rồi, thời tiết ấm áp lên rồi."),
            v("凉快", "liángkuai", "Lương Khoái", "Mát mẻ, dễ chịu", "Tính từ", "Thời tiết & Khí hậu", "Bộ: 冫 (Băng)", "17 nét", "秋天下雨后真凉快。", "Qiūtiān xiàyǔ hòu zhēn liángkuai.", "Mùa thu sau cơn mưa thật là mát mẻ."),
            v("好", "hǎo", "Hảo", "Tốt, đẹp, hay, khỏe", "Tính từ", "Chào hỏi & Giao tiếp", "Bộ: 女 (Nữ)", "6 nét", "今天天气很好。", "Jīntiān tiānqì hěn hǎo.", "Thời tiết hôm nay rất tốt."),
            v("坏", "huài", "Hoại", "Xấu, hỏng, tồi", "Tính từ", "Cảm xúc & Tâm trạng", "Bộ: 土 (Thổ)", "7 nét", "手机坏了，不能打电话。", "Shǒujī huài le, bù néng dǎ diànhuà.", "Điện thoại hỏng rồi, không thể gọi được nữa."),
            v("大", "dà", "Đại", "To, lớn", "Tính từ", "Cảm xúc & Tâm trạng", "Bộ: 大 (Đại)", "3 nét", "西瓜很大很甜。", "Xīguā hěn dà hěn tián.", "Quả dưa hấu rất to và ngọt."),
            v("小", "xiǎo", "Tiểu", "Nhỏ, bé", "Tính từ", "Động vật & Thiên nhiên", "Bộ: 小 (Tiểu)", "3 nét", "这个房间太小了。", "Zhège fángjiān tài xiǎo le.", "Căn phòng này nhỏ quá."),
            v("多", "duō", "Đa", "Nhiều", "Tính từ", "Số đếm & Mua sắm", "Bộ: 夕 (Tịch)", "6 nét", "学校里有很多学生。", "Xuéxiào lǐ yǒu hěn duō xuésheng.", "Trong trường có rất nhiều học sinh."),
            v("少", "shǎo", "Thiểu", "Ít", "Tính từ", "Số đếm & Mua sắm", "Bộ: 小 (Tiểu)", "4 nét", "今天来的人很少。", "Jīntiān lái de rén hěn shǎo.", "Người đến hôm nay rất ít."),
            v("长", "cháng", "Trường", "Dài", "Tính từ", "Trang phục & Thời trang", "Bộ: 长 (Trường)", "4 nét", "这条路很长。", "Zhè tiáo lù hěn cháng.", "Con đường này rất dài."),
            v("短", "duǎn", "Đoản", "Ngắn", "Tính từ", "Trang phục & Thời trang", "Bộ: 矢 (Thỉ)", "12 nét", "这件衣服有点短。", "Zhè jiàn yīfu yǒudiǎn duǎn.", "Chiếc áo này hơi ngắn một chút."),
            v("高", "gāo", "Cao", "Cao", "Tính từ", "Gia đình & Đời sống", "Bộ: 高 (Cao)", "10 nét", "弟弟长得很高。", "Dìdi zhǎng de hěn gāo.", "Em trai lớn lên rất cao lớn."),
            v("矮", "ǎi", "Ải", "Thấp, lùn", "Tính từ", "Gia đình & Đời sống", "Bộ: 矢 (Thỉ)", "13 nét", "小椅子矮矮的。", "Xiǎo yǐzi ǎi'ǎi de.", "Chiếc ghế nhỏ thấp thấp."),
            v("远", "yuǎn", "Viễn", "Xa", "Tính từ", "Phương hướng & Vị trí", "Bộ: 辶 (Sước)", "7 nét", "学校离我家很远。", "Xuéxiào lí wǒ jiā hěn yuǎn.", "Trường học cách nhà tôi rất xa."),
            v("近", "jìn", "Cận", "Gần", "Tính từ", "Phương hướng & Vị trí", "Bộ: 辶 (Sước)", "7 nét", "超市就在附近，很近。", "Chāoshì jiù zài fùjìn, hěn jìn.", "Siêu thị ở ngay gần đây, rất gần."),
            v("快", "kuài", "Khoái", "Nhanh / Sắp", "Tính từ / Phó từ", "Đi lại & Du lịch", "Bộ: 忄 (Tâm)", "7 nét", "高铁跑得真快。", "Gāotiě pǎo de zhēn kuài.", "Tàu cao tốc chạy thật là nhanh."),
            v("慢", "màn", "Mạn", "Chậm, từ tốn", "Tính từ", "Đi lại & Du lịch", "Bộ: 忄 (Tâm)", "14 nét", "请说慢一点儿。", "Qǐng shuō màn yìdiǎnr.", "Xin hãy nói chậm lại một chút."),
            v("新", "xīn", "Tân", "Mới", "Tính từ", "Số đếm & Mua sắm", "Bộ: 斤 (Cân)", "13 nét", "我买了一辆新自行车。", "Wǒ mǎi le yí liàng xīn zìxíngchē.", "Tôi đã mua một chiếc xe đạp mới."),
            v("旧", "jiù", "Cựu", "Cũ", "Tính từ", "Số đếm & Mua sắm", "Bộ: 日 (Nhật)", "5 nét", "旧衣服不要扔。", "Jiù yīfu bú yào rēng.", "Quần áo cũ đừng vứt đi nhé."),
            v("忙", "máng", "Mang", "Bận rộn, bận", "Tính từ", "Công việc & Công sở", "Bộ: 忄 (Tâm)", "6 nét", "爸爸今天非常忙。", "Bàba jīntiān fēicháng máng.", "Hôm nay bố cực kỳ bận rộn."),
            v("错", "cuò", "Thác", "Sai, nhầm lẫn / Tồi", "Tính từ", "Học tập & Giáo dục", "Bộ: 钅 (Kim)", "13 nét", "这道题你做错了。", "Zhè dào tí nǐ zuò cuò le.", "Câu này bạn làm sai rồi."),
            v("便宜", "piányi", "Tiện Nghi", "Rẻ (giá cả)", "Tính từ", "Số đếm & Mua sắm", "Bộ: 亻 (Nhân)", "17 nét", "衣服挺便宜的。", "Yīfu tǐng piányi de.", "Quần áo khá là rẻ."),
            v("贵", "guì", "Quý", "Đắt (tiền) / Quý", "Tính từ", "Số đếm & Mua sắm", "Bộ: 贝 (Bối)", "9 nét", "太贵了，便宜一点吧。", "Tài guì le, piányi yìdiǎn ba.", "Đắt quá, bớt cho tôi một chút đi."),
            v("漂亮", "piàoliang", "Phiêu Lượng", "Đẹp, xinh đẹp", "Tính từ", "Trang phục & Thời trang", "Bộ: 氵 (Thủy)", "23 nét", "那个女孩真漂亮。", "Nàge nǚhái zhēn piàoliang.", "Cô gái đó thật là xinh đẹp."),
            v("好看", "hǎokàn", "Hảo Khán", "Đẹp mắt, ưa nhìn", "Tính từ", "Trang phục & Thời trang", "Bộ: 女 (Nữ)", "15 nét", "这部电影真好看。", "Zhè bù diànyǐng zhēn hǎokàn.", "Bộ phim này xem hay và đẹp thật đấy."),
            v("干净", "gānjìng", "Can Tịnh", "Sạch sẽ", "Tính từ", "Nhà cửa & Đồ dùng", "Bộ: 干 (Can)", "11 nét", "房间打扫得很干净。", "Fángjiān dǎsǎo de hěn gānjìng.", "Phòng ốc được dọn dẹp rất sạch sẽ."),
            v("脏", "zāng", "Tạng", "Bẩn, dơ", "Tính từ", "Nhà cửa & Đồ dùng", "Bộ: 月 (Nguyệt)", "10 nét", "衣服脏了，要洗洗。", "Yīfu zāng le, yào xǐxǐ.", "Áo bẩn rồi, phải giặt giũ thôi."),
            v("简单", "jiǎndān", "Giản Đơn", "Đơn giản, dễ dàng", "Tính từ", "Học tập & Giáo dục", "Bộ: 竹 (Trúc)", "20 nét", "这个问题很简单。", "Zhège wèntí hěn jiǎndān.", "Vấn đề này rất đơn giản."),
            v("难", "nán", "Nan", "Khó khăn, gian nan", "Tính từ", "Học tập & Giáo dục", "Bộ: 又 (Hựu)", "10 nét", "汉字有点难写。", "Hànzì yǒudiǎn nán xiě.", "Chữ Hán hơi khó viết một chút."),
            v("容易", "róngyì", "Dung Dị", "Dễ, dễ dàng", "Tính từ", "Học tập & Giáo dục", "Bộ: 宀 (Miên)", "18 nét", "这道数学题很容易。", "Zhè dào shùxué tí hěn róngyì.", "Bài toán này rất dễ."),
            v("清楚", "qīngchu", "Thanh Sở", "Rõ ràng, rành mạch", "Tính từ", "Học tập & Giáo dục", "Bộ: 氵 (Thủy)", "24 nét", "请说清楚一点儿。", "Qǐng shuō qīngchu yìdiǎnr.", "Xin hãy nói rõ ràng hơn một chút."),
            v("红", "hóng", "Hồng", "Màu đỏ", "Tính từ / Danh từ", "Màu sắc & Hình dáng", "Bộ: 纟 (Mịch)", "6 nét", "红色的苹果。", "Hóngsè de píngguǒ.", "Quả táo màu đỏ."),
            v("白", "bái", "Bạch", "Màu trắng", "Tính từ / Danh từ", "Màu sắc & Hình dáng", "Bộ: 白 (Bạch)", "5 nét", "她穿一件白衬衫。", "Tā chuān yí jiàn bái chènshān.", "Cô ấy mặc một chiếc áo sơ mi trắng."),
            v("黑", "hēi", "Hắc", "Màu đen, tối", "Tính từ / Danh từ", "Màu sắc & Hình dáng", "Bộ: 黑 (Hắc)", "12 nét", "他戴着一副黑眼镜。", "Tā dài zhe yí fù hēi yǎnjìng.", "Anh ấy đeo một chiếc kính màu đen."),
            v("黄", "huáng", "Hoàng", "Màu vàng", "Tính từ / Danh từ", "Màu sắc & Hình dáng", "Bộ: 黄 (Hoàng)", "11 nét", "秋天树叶变黄了。", "Qiūtiān shùyè biàn huáng le.", "Mùa thu lá cây chuyển sang màu vàng."),
            v("蓝", "lán", "Lam", "Màu xanh da trời, xanh lam", "Tính từ / Danh từ", "Màu sắc & Hình dáng", "Bộ: 艹 (Thảo)", "13 nét", "天是蓝色的。", "Tiān shì lánsè de.", "Bầu trời có màu xanh lam."),
            v("绿", "lǜ", "Lục", "Màu xanh lá cây", "Tính từ / Danh từ", "Màu sắc & Hình dáng", "Bộ: 纟 (Mịch)", "11 nét", "春天草地是绿的。", "Chūntiān cǎodì shì lǜ de.", "Mùa xuân bãi cỏ có màu xanh lá."),

            // ── 17. HÀNH ĐỘNG, CẢM XÚC & XÃ HỘI (ACTIONS, EMOTIONS & SOCIAL) ──
            v("爱", "ài", "Ái", "Yêu, thích", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 爫 (Trảo)", "10 nét", "我爱我的爸爸妈妈。", "Wǒ ài wǒ de bàba māma.", "Tôi yêu ba mẹ của tôi."),
            v("喜欢", "xǐhuan", "Hỷ Hoan", "Thích, ưa thích", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 士 (Sĩ)", "18 nét", "我喜欢学中国话。", "Wǒ xǐhuan xué Zhōngguóhuà.", "Tôi thích học tiếng Trung."),
            v("怕", "pà", "Phạ", "Sợ, e sợ", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 忄 (Tâm)", "8 nét", "别怕，我在这儿。", "Bié pà, wǒ zài zhèr.", "Đừng sợ, có tôi ở đây rồi."),
            v("哭", "kū", "Khốc", "Khóc", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 口 (Khẩu)", "10 nét", "那个小孩子哭了。", "Nàge xiǎoháizi kū le.", "Đứa bé đó khóc rồi."),
            v("笑", "xiào", "Tiếu", "Cười, mỉm cười", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 竹 (Trúc)", "10 nét", "老师笑着对我们说话。", "Lǎoshī xiào zhe duì wǒmen shuōhuà.", "Cô giáo cười tươi nói chuyện với chúng tôi."),
            v("高兴", "gāoxìng", "Cao Hưng", "Vui mừng, phấn khởi", "Tính từ", "Cảm xúc & Tâm trạng", "Bộ: 高 (Cao)", "16 nét", "今天大家都很高兴。", "Jīntiān dàjiā dōu hěn gāoxìng.", "Hôm nay mọi người đều rất vui vẻ."),
            v("快乐", "kuàilè", "Khoái Lạc", "Vui vẻ, hạnh phúc", "Tính từ", "Cảm xúc & Tâm trạng", "Bộ: 忄 (Tâm)", "12 nét", "祝你天天快乐！", "Zhù nǐ tiāntiān kuàilè!", "Chúc bạn mỗi ngày đều tràn ngập niềm vui!"),
            v("开心", "kāixīn", "Khai Tâm", "Vui vẻ, hớn hở", "Tính từ", "Cảm xúc & Tâm trạng", "Bộ: 廾 (Củng)", "8 nét", "今天玩得真开心。", "Jīntiān wán de zhēn kāixīn.", "Hôm nay đi chơi thật là vui."),
            v("生气", "shēngqì", "Sinh Khí", "Tức giận, giận hờn", "Động từ / Tính từ", "Cảm xúc & Tâm trạng", "Bộ: 生 (Sinh)", "9 nét", "别生气了，笑一个。", "Bié shēngqì le, xiào yí gè.", "Đừng giận nữa mà, cười một cái đi."),
            v("担心", "dānxīn", "Đam Tâm", "Lo lắng, bận tâm", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 扌 (Thủ)", "12 nét", "妈妈很担心我的身体。", "Māma hěn dānxīn wǒ de shēntǐ.", "Mẹ rất lo lắng cho sức khỏe của tôi."),
            v("想", "xiǎng", "Tưởng", "Nghĩ, muốn, nhớ", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 心 (Tâm)", "13 nét", "我想妈妈了。", "Wǒ xiǎng māma le.", "Tôi nhớ mẹ rồi."),
            v("要", "yào", "Yếu", "Muốn, cần, phải", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 覀 (Á)", "9 nét", "我要一杯冰红茶。", "Wǒ yào yì bēi bīng hóngchá.", "Tôi muốn một cốc hồng trà đá."),
            v("能", "néng", "Năng", "Có thể (năng lực, điều kiện)", "Động từ năng nguyện", "Học tập & Giáo dục", "Bộ: 月 (Nguyệt)", "10 nét", "你能帮我一个忙吗？", "Nǐ néng bāng wǒ yí gè máng ma?", "Bạn có thể giúp tôi một tay được không?"),
            v("可以", "kěyǐ", "Khả Dĩ", "Có thể, được phép", "Động từ năng nguyện", "Chào hỏi & Giao tiếp", "Bộ: 口 (Khẩu)", "9 nét", "我可以坐在这儿吗？", "Wǒ kěyǐ zuò zài zhèr ma?", "Tôi có thể ngồi ở đây được không?"),
            v("会", "huì", "Hội", "Biết (qua rèn luyện) / Sẽ", "Động từ năng nguyện", "Học tập & Giáo dục", "Bộ: 人 (Nhân)", "6 nét", "我会说一点汉语。", "Wǒ huì shuō yìdiǎn Hànyǔ.", "Tôi biết nói một chút tiếng Trung."),
            v("敢", "gǎn", "Cảm", "Dám", "Động từ năng nguyện", "Cảm xúc & Tâm trạng", "Bộ: 攵 (Phác)", "11 nét", "他不敢一个人走夜路。", "Tā bù gǎn yí gè rén zǒu yèlù.", "Cậu ấy không dám một mình đi đường tối."),
            v("应该", "yīnggāi", "Ưng Cai", "Nên, phải", "Động từ năng nguyện", "Học tập & Giáo dục", "Bộ: 广 (Quảng)", "17 nét", "我们应该每天练习汉语。", "Wǒmen yīnggāi měitiān liànxí Hànyǔ.", "Chúng ta nên luyện tập tiếng Trung mỗi ngày."),
            v("希望", "xīwàng", "Hy Vọng", "Hy vọng, mong muốn", "Động từ / Danh từ", "Cảm xúc & Tâm trạng", "Bộ: 巾 (Cân)", "18 nét", "希望你考试取得好成绩。", "Xīwàng nǐ kǎoshì qǔdé hǎo chéngjì.", "Hy vọng bạn thi cử đạt được thành tích tốt."),
            v("准备", "zhǔnbèi", "Chuẩn Bị", "Chuẩn bị", "Động từ", "Học tập & Giáo dục", "Bộ: 冫 (Băng)", "17 nét", "我准备好了，可以出发。", "Wǒ zhǔnbèi hǎo le, kěyǐ chūfā.", "Tôi chuẩn bị xong rồi, có thể xuất phát."),
            v("开始", "kāishǐ", "Khai Thủy", "Bắt đầu", "Động từ", "Thời gian & Ngày tháng", "Bộ: 廾 (Củng)", "12 nét", "考试现在开始了。", "Kǎoshì xiànzài kāishǐ le.", "Kỳ thi bây giờ bắt đầu rồi."),
            v("结束", "jiéshù", "Kết Thúc", "Kết thúc, chấm dứt", "Động từ", "Thời gian & Ngày tháng", "Bộ: 纟 (Mịch)", "20 nét", "会议下午四点结束。", "Huìyì xiàwǔ sì diǎn jiéshù.", "Cuộc họp kết thúc lúc 4 giờ chiều."),
            v("完", "wán", "Hoàn", "Xong, hết, hoàn thành", "Động từ", "Thời gian & Ngày tháng", "Bộ: 宀 (Miên)", "7 nét", "作业我已经做完了。", "Zuòyè wǒ yǐjīng zuòwán le.", "Bài tập tôi đã làm xong rồi."),
            v("看见", "kànjiàn", "Khán Kiến", "Nhìn thấy, trông thấy", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 目 (Mục)", "13 nét", "我看见王老师来了。", "Wǒ kànjiàn Wáng lǎoshī lái le.", "Tôi nhìn thấy thầy Vương đến rồi."),
            v("听见", "tīngjiàn", "Thính Kiến", "Nghe thấy, nghe được", "Động từ", "Học tập & Giáo dục", "Bộ: 口 (Khẩu)", "11 nét", "你听见有人敲门吗？", "Nǐ tīngjiàn yǒu rén qiāomén ma?", "Bạn có nghe thấy ai gõ cửa không?"),
            v("找", "zhǎo", "Trảo", "Tìm kiếm / Thối tiền", "Động từ", "Số đếm & Mua sắm", "Bộ: 扌 (Thủ)", "7 nét", "你在找什么呢？", "Nǐ zài zhǎo shénme ne?", "Bạn đang tìm cái gì thế?"),
            v("买", "mǎi", "Mãi", "Mua", "Động từ", "Số đếm & Mua sắm", "Bộ: 乙 (Ất)", "6 nét", "我想买几个苹果。", "Wǒ xiǎng mǎi jǐ gè píngguǒ.", "Tôi muốn mua mấy quả táo."),
            v("卖", "mài", "Mại", "Bán", "Động từ", "Số đếm & Mua sắm", "Bộ: 十 (Thập)", "8 nét", "这家店卖新鲜面包。", "Zhè jiā diàn mài xīnxiān miànbāo.", "Cửa hàng này bán bánh mì tươi."),
            v("送", "sòng", "Tống", "Tặng / Tiễn đưa", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 辶 (Sước)", "9 nét", "我送你一本好书。", "Wǒ sòng nǐ yì běn hǎo shū.", "Tôi tặng bạn một cuốn sách hay."),
            v("借", "jiè", "Tá", "Mượn, vay", "Động từ", "Học tập & Giáo dục", "Bộ: 亻 (Nhân)", "10 nét", "我想借你的笔用一下。", "Wǒ xiǎng jiè nǐ de bǐ yòng yíxià.", "Tôi muốn mượn bút bạn dùng một chút."),
            v("带", "dài", "Đới", "Mang theo, dẫn theo", "Động từ", "Gia đình & Đời sống", "Bộ: 巾 (Cân)", "9 nét", "出门别忘了带手机。", "Chūmén bié wàng le dài shǒujī.", "Ra khỏi cửa đừng quên mang điện thoại."),
            v("拿", "ná", "Nã", "Cầm, nắm, lấy", "Động từ", "Nhà cửa & Đồ dùng", "Bộ: 手 (Thủ)", "10 nét", "请帮我拿一下包。", "Qǐng bāng wǒ ná yíxià bāo.", "Làm ơn cầm giúp tôi chiếc túi với."),
            v("放", "fàng", "Phóng", "Đặt, để", "Động từ", "Nhà cửa & Đồ dùng", "Bộ: 攵 (Phác)", "8 nét", "请把书放在桌子上。", "Qǐng bǎ shū fàng zài zhuōzi shàng.", "Xin hãy đặt sách lên bàn."),
            v("穿", "chuān", "Xuyên", "Mặc (quần áo, giày dép)", "Động từ", "Trang phục & Thời trang", "Bộ: 穴 (Huyệt)", "9 nét", "外面冷，穿上大衣吧。", "Wàimian lěng, chuānshang dàyī ba.", "Bên ngoài lạnh, mặc áo khoác vào đi."),
            v("戴", "dài", "Đái", "Đeo, đội (mũ, kính, găng)", "Động từ", "Trang phục & Thời trang", "Bộ: 戈 (Qua)", "17 nét", "他戴着一顶黑帽子。", "Tā dài zhe yì dǐng hēi màozi.", "Anh ấy đội một chiếc mũ màu đen."),
            v("洗", "xǐ", "Tẩy", "Rửa, giặt", "Động từ", "Nhà cửa & Đồ dùng", "Bộ: 氵 (Thủy)", "9 nét", "洗手洗脸。", "Xǐshǒu xǐliǎn.", "Rửa tay rửa mặt."),
            v("打", "dǎ", "Đả", "Đánh, chơi (bóng) / Bắt (xe)", "Động từ", "Thể thao & Vận động", "Bộ: 扌 (Thủ)", "5 nét", "下午我们去打篮球。", "Xiàwǔ wǒmen qù dǎ lánqiú.", "Chiều nay chúng mình đi chơi bóng rổ."),
            v("踢", "tī", "Thích", "Đá (bóng)", "Động từ", "Thể thao & Vận động", "Bộ: 足 (Túc)", "15 nét", "男孩子们在操场踢足球。", "Nánháizimen zài cāochǎng tī zúqiú.", "Các cậu bé đang đá bóng trên sân."),
            v("玩", "wán", "Ngoạn", "Chơi, vui chơi", "Động từ", "Giải trí & Sở thích", "Bộ: 王 (Vương)", "8 nét", "周末我们去公园玩吧。", "Zhōumò wǒmen qù gōngyuán wán ba.", "Cuối tuần chúng mình đi công viên chơi đi."),
            v("唱歌", "chànggē", "Xướng Ca", "Hát, ca hát", "Động từ", "Giải trí & Sở thích", "Bộ: 口 (Khẩu)", "25 nét", "妹妹很喜欢唱歌。", "Mèimei hěn xǐhuan chànggē.", "Em gái rất thích ca hát."),
            v("跳舞", "tiàowǔ", "Khiêu Vũ", "Múa, khiêu vũ", "Động từ", "Giải trí & Sở thích", "Bộ: 足 (Túc)", "27 nét", "他们正在高兴地跳舞。", "Tāmen zhèngzài gāoxìng de tiàowǔ.", "Họ đang vui vẻ khiêu vũ cùng nhau."),
            v("运动", "yùndòng", "Vận Động", "Vận động, thể thao", "Động từ / Danh từ", "Thể thao & Vận động", "Bộ: 辶 (Sước)", "16 nét", "每天运动半小时。", "Měitiān yùndòng bàn xiǎoshí.", "Mỗi ngày vận động nửa tiếng."),
            v("跑步", "pǎobù", "Bào Bộ", "Chạy bộ", "Động từ", "Thể thao & Vận động", "Bộ: 足 (Túc)", "19 nét", "早上六点在操场跑步。", "Zǎoshang liù diǎn zài cāochǎng pǎobù.", "Sáu giờ sáng chạy bộ trên sân vận động."),
            v("游泳", "yóuyǒng", "Du Vịnh", "Bơi lội", "Động từ", "Thể thao & Vận động", "Bộ: 氵 (Thủy)", "20 nét", "夏天在河里游泳很凉快。", "Xiàtiān zài hé lǐ yóuyǒng hěn liángkuai.", "Mùa hè bơi ở sông rất mát mẻ."),
            v("散步", "sànbù", "Tản Bộ", "Đi dạo, tản bộ", "Động từ", "Gia đình & Đời sống", "Bộ: 攵 (Phác)", "19 nét", "晚饭后我们常常去散步。", "Wǎnfàn hòu wǒmen chángcháng qù sànbù.", "Sau bữa tối chúng tôi thường đi dạo."),
            v("见面", "jiànmiàn", "Kiến Diện", "Gặp mặt, gặp gỡ", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 见 (Kiến)", "13 nét", "很高兴与你见面。", "Hěn gāoxìng yǔ nǐ jiànmiàn.", "Rất vui được gặp mặt bạn."),
            v("介绍", "jièshào", "Giới Thiệu", "Giới thiệu", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 人 (Nhân)", "12 nét", "请向大家介绍一下你自己。", "Qǐng xiàng dàjiā jièshào yíxià nǐ zìjǐ.", "Xin hãy giới thiệu một chút về bản thân bạn với mọi người."),
            v("欢迎", "huānyíng", "Hoan Nghênh", "Chào đón, hoan nghênh", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 欠 (Khiếm)", "13 nét", "热烈欢迎各位新同学！", "Rèliè huānyíng gè wèi xīn tóngxué!", "Nhiệt liệt chào đón các bạn học sinh mới!"),
            v("请客", "qǐngkè", "Thỉnh Khách", "Mời khách, bao chầu", "Động từ", "Ăn uống & Ẩm thực", "Bộ: 讠 (Ngôn)", "19 nét", "今天我请客，大家放开吃！", "Jīntiān wǒ qǐngkè, dàjiā fàngkāi chī!", "Hôm nay tôi mời, mọi người cứ thoải mái ăn uống nhé!"),
            v("祝", "zhù", "Chúc", "Chúc, cầu chúc", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 礻 (Thị)", "9 nét", "祝你一路平安！", "Zhù nǐ yílù píng'ān!", "Chúc bạn thượng lộ bình an!"),
            v("帮助", "bāngzhù", "Bang Trợ", "Giúp đỡ", "Động từ / Danh từ", "Chào hỏi & Giao tiếp", "Bộ: 巾 (Cân)", "16 nét", "多谢你的热情帮助。", "Duōxiè nǐ de rèqíng bāngzhù.", "Cảm ơn rất nhiều sự giúp đỡ nhiệt tình của bạn."),
            v("关心", "guānxīn", "Quan Tâm", "Quan tâm, săn sóc", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 门 (Môn)", "10 nét", "父母非常关心我的学习。", "Fùmǔ fēicháng guānxīn wǒ de xuéxí.", "Bố mẹ rất quan tâm đến việc học của tôi."),
            v("照顾", "zhàogù", "Chiếu Cố", "Chăm sóc, trông nom", "Động từ", "Gia đình & Đời sống", "Bộ: 灬 (Hỏa)", "26 nét", "在家里照顾小弟弟。", "Zài jiā lǐ zhàogù xiǎo dìdi.", "Ở nhà chăm sóc em trai nhỏ."),
            v("放心", "fàngxīn", "Phóng Tâm", "Yên tâm, an lòng", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 攵 (Phác)", "12 nét", "您放心，我一定会努力的。", "Nín fàngxīn, wǒ yídìng huì nǔlì de.", "Bác yên tâm, cháu nhất định sẽ nỗ lực."),
            v("忘", "wàng", "Vong", "Quên", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 心 (Tâm)", "7 nét", "我忘了带今天的作业。", "Wǒ wàng le dài jīntiān de zuòyè.", "Tôi quên mang bài tập hôm nay rồi."),
            v("记得", "jìde", "Ký Đắc", "Ghi nhớ, còn nhớ", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 讠 (Ngôn)", "19 nét", "你还记得我叫什么吗？", "Nǐ hái jìde wǒ jiào shénme ma?", "Bạn còn nhớ tôi tên là gì không?"),
            v("觉得", "juéde", "Giác Đắc", "Cảm thấy, thấy rằng", "Động từ", "Cảm xúc & Tâm trạng", "Bộ: 见 (Kiến)", "18 nét", "我觉得这本汉语书很好。", "Wǒ juéde zhè běn Hànyǔ shū hěn hǎo.", "Tôi cảm thấy cuốn sách tiếng Trung này rất hay."),
            v("同意", "tóngyì", "Đồng Ý", "Đồng ý, tán thành", "Động từ", "Chào hỏi & Giao tiếp", "Bộ: 口 (Khẩu)", "19 nét", "大家都同意这个想法。", "Dàjiā dōu tóngyì zhège xiǎngfǎ.", "Mọi người đều đồng ý với ý kiến này."),

            // ── 18. THÀNH NGỮ & CỤM TỪ CỐ ĐỊNH CHUẨN ĐẦU RA HSK 1 ──
            v("你好", "nǐ hǎo", "Nhĩ Hảo", "Xin chào, chào bạn", "Cụm từ cố định", "Chào hỏi & Giao tiếp", "Bộ: 亻 (Nhân)", "7 nét", "你好，很高兴认识你！", "Nǐ hǎo, hěn gāoxìng rènshí nǐ!", "Xin chào, rất vui được làm quen với bạn!"),
            v("谢谢", "xièxie", "Tạ Tạ", "Cảm ơn", "Động từ / Cụm từ", "Chào hỏi & Giao tiếp", "Bộ: 讠 (Ngôn)", "24 nét", "谢谢你的热情帮助！", "Xièxie nǐ de rèqíng bāngzhù!", "Cảm ơn sự giúp đỡ nhiệt tình của bạn!"),
            v("不客气", "bú kèqi", "Bất Khách Khí", "Không có gì, đừng khách sáo", "Cụm từ cố định", "Chào hỏi & Giao tiếp", "Bộ: 一 (Nhất)", "17 nét", "不客气，这是我应该做的。", "Bú kèqi, zhè shì wǒ yīnggāi zuò de.", "Không có gì đâu, đây là điều tôi nên làm mà."),
            v("对不起", "duìbuqǐ", "Đối Bất Khởi", "Xin lỗi", "Cụm từ cố định", "Chào hỏi & Giao tiếp", "Bộ: 寸 (Thốn)", "19 nét", "对不起，我来晚了。", "Duìbuqǐ, wǒ lái wǎn le.", "Xin lỗi nhé, tôi tới muộn mất rồi."),
            v("没关系", "méi guānxi", "Một Quan Hệ", "Không sao, không có chi", "Cụm từ cố định", "Chào hỏi & Giao tiếp", "Bộ: 氵 (Thủy)", "18 nét", "没关系，我也刚到。", "Méi guānxi, wǒ yě gāng dào.", "Không sao đâu, tôi cũng vừa mới tới thôi."),
            v("再见", "zàijiàn", "Tái Kiến", "Tạm biệt, hẹn gặp lại", "Cụm từ cố định", "Chào hỏi & Giao tiếp", "Bộ: 冂 (Quynh)", "10 nét", "明天见，再见！", "Míngtiān jiàn, zàijiàn!", "Ngày mai gặp lại, tạm biệt nhé!"),
            v("请问", "qǐngwèn", "Thỉnh Vấn", "Xin hỏi, làm ơn cho hỏi", "Cụm từ cố định", "Chào hỏi & Giao tiếp", "Bộ: 讠 (Ngôn)", "16 nét", "请问去地铁站怎么走？", "Qǐngwèn qù dìtiězhàn zěnme zǒu?", "Xin hỏi đường đi đến ga tàu điện ngầm đi thế nào ạ?")
        )
    }
}
